Repository Icinga/icingaweb2, pull requests merged in 2018-02, with the labels that each got.

#3354 protocol is wrong, fcgi, not fgci
  modules/setup/library/Setup/Webserver/Apache.php
Labels: bug, documentation

#3360 Vagrant: Install SCL PHP CLI and set PATH
  .puppet/files/etc/profile.d/env.sh
  .puppet/profiles/icingaweb2_dev/manifests/init.pp
Labels: Vagrant VM, bug

#3364 Vagrant: Fix missing mbstring PHP module
  .puppet/profiles/icingaweb2_dev/manifests/init.pp
Labels: Vagrant VM, bug

#3363 Vagrant: Introduce base profile and install vim
  .puppet/manifests/site.pp
  .puppet/profiles/base/manifests/init.pp
Labels: Vagrant VM

#3368 TacticalController: Add OutputFormat json and csv
  modules/monitoring/application/controllers/TacticalController.php
Labels: Print & Export, enhancement
