Repository Icinga/icingaweb2, pull requests merged in 2018-07, with the labels that each got.

#3421 Documentation for the webserver installation on Debian
  doc/02-Installation.md
Labels: documentation, needs-feedback

#3503 Let redirectHttp use HTTP for redirection
  library/Icinga/Web/Controller/ActionController.php
  public/js/icinga/loader.js
Labels: enhancement, framework

#3486 Fix that Request parses json without respecting content type
  library/Icinga/Web/Request.php
Labels: bug, framework

#3521 Fix some XSS vulnerabilities
  application/layouts/scripts/body.phtml
  application/views/scripts/mixedPagination.phtml
  library/Icinga/Web/Widget/Tab.php
  library/Icinga/Web/Widget/Tabs.php
Labels: QA, bug

#3524 monitoring: Introduce run.php and provide the new ApplicationStateHook
  modules/monitoring/run.php
Labels: bug, monitoring

#3519 Pdo\Abstract: Properly handle incomplete error messages
  library/vendor/Zend/Db/Adapter/Pdo/Abstract.php
Labels: Vendor Libraries, bug

#3518 loader.js: Make anchor navigation working again
  public/js/icinga/loader.js
Labels: JavaScript, bug

#3533 Add command audit
  modules/monitoring/library/Monitoring/Command/Transport/ApiCommandTransport.php
Labels: enhancement, monitoring

#3457 Proper results when filtering for linked objects
  modules/monitoring/library/Monitoring/Backend/Ido/Query/ContactgroupQuery.php
  modules/monitoring/library/Monitoring/Backend/Ido/Query/HostcommentQuery.php
  modules/monitoring/library/Monitoring/Backend/Ido/Query/HostcommenthistoryQuery.php
  modules/monitoring/library/Monitoring/Backend/Ido/Query/HostcontactQuery.php
  modules/monitoring/library/Monitoring/Backend/Ido/Query/HostdowntimeQuery.php
  modules/monitoring/library/Monitoring/Backend/Ido/Query/HostdowntimestarthistoryQuery.php
  modules/monitoring/library/Monitoring/Backend/Ido/Query/HostflappingstarthistoryQuery.php
  modules/monitoring/library/Monitoring/Backend/Ido/Query/HostgroupQuery.php
  modules/monitoring/library/Monitoring/Backend/Ido/Query/HostnotificationQuery.php
  modules/monitoring/library/Monitoring/Backend/Ido/Query/HoststatehistoryQuery.php
  modules/monitoring/library/Monitoring/Backend/Ido/Query/HoststatusQuery.php
  modules/monitoring/library/Monitoring/Backend/Ido/Query/IdoQuery.php
  modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicecommentQuery.php
  modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicecommenthistoryQuery.php
  modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicecontactQuery.php
  modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicedowntimeQuery.php
  modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicedowntimestarthistoryQuery.php
  modules/monitoring/library/Monitoring/Backend/Ido/Query/ServiceflappingstarthistoryQuery.php
  modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicegroupQuery.php
  modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicenotificationQuery.php
  modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicestatehistoryQuery.php
  modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicestatusQuery.php
Labels: enhancement, monitoring
