Repository Icinga/icingaweb2, pull requests merged in 2018-04, with the labels that each got.

#3409 Fix missing german tactical overview translations
  modules/monitoring/application/controllers/TacticalController.php
  modules/monitoring/application/locale/de_DE/LC_MESSAGES/monitoring.mo
  modules/monitoring/application/locale/de_DE/LC_MESSAGES/monitoring.po
  modules/monitoring/application/views/scripts/tactical/index.phtml
  public/css/icinga/widgets.less
Labels: I18N/L10N, bug

#3410 menu: Only invert icons located under /img/icons/
  public/css/icinga/menu.less
Labels: bug

#3411 Fix that dashboard panes cannot be renamed
  application/controllers/DashboardController.php
  application/views/scripts/dashboard/rename-pane.phtml
  application/views/scripts/dashboard/settings.phtml
  library/Icinga/Web/Widget/Dashboard/Pane.php
Labels: bug

#3400 Platform: Correct detecting MSSQL Support
  library/Icinga/Application/Platform.php
Labels: bug, framework

#3424 Do not mangle cursor position in forms
  public/js/icinga/loader.js
Labels: JavaScript, bug

#3426 Add support for the sqlsrv extension
  library/Icinga/Application/Platform.php
  library/Icinga/Data/Db/DbConnection.php
Labels: enhancement, framework

#3425 Don't search as long as the user is typing
  public/js/icinga/events.js
Labels: JavaScript, enhancement

#3383 PluginOutput: Fix text splicing for status tags in HTML output
  modules/monitoring/application/views/helpers/PluginOutput.php
  modules/monitoring/test/php/application/views/helpers/PluginOutputTest.php
Labels: bug
