Repository Icinga/icingaweb2, pull requests merged in 2018-12, with the labels that each got.

#3634 Use continue <N> in case statements to fix ErrorException with PHP 7.3.
  library/Icinga/Application/Modules/Module.php
  library/Icinga/File/Ini/IniParser.php
Labels: bug

#3645 vendor: Update zf1 for PHP 7.3
  library/vendor/Zend/Form.php
  library/vendor/Zend/README.md
  library/vendor/Zend/VERSION
Labels: bug

#3637 Ensure PHP 7.3 works
  .gitignore
  .travis.yml
  library/Icinga/Chart/GridChart.php
  library/vendor/JShrink/Minifier.php
  library/vendor/JShrink/SOURCE
  library/vendor/dompdf/SOURCE
  library/vendor/dompdf/lib/Cpdf.php
  library/vendor/dompdf/src/Adapter/CPDF.php
  library/vendor/dompdf/src/Adapter/GD.php
  library/vendor/dompdf/src/Adapter/PDFLib.php
  library/vendor/dompdf/src/Css/Stylesheet.php
  library/vendor/dompdf/src/Dompdf.php
  library/vendor/dompdf/src/FontMetrics.php
  library/vendor/dompdf/src/FrameDecorator/Page.php
  library/vendor/dompdf/src/Image/Cache.php
  library/vendor/dompdf/src/Renderer/AbstractRenderer.php
  library/vendor/dompdf/src/Renderer/Text.php
  phpcs.xml
  test/check-syntax.php
  test/php/bootstrap.php
  test/setup_vendor.sh
Labels: QA

#3643 DbConnection: Make host optional for Oracle connections
  application/forms/Config/Resource/DbResourceForm.php
  library/Icinga/Data/Db/DbConnection.php
Labels: enhancement

#3640 Respect php.ini limits when exporting to PDF
  library/Icinga/File/Pdf.php
  library/Icinga/Util/Environment.php
  library/Icinga/Util/Format.php
  test/php/library/Icinga/Util/EnvironmentTest.php
Labels: bug

#3649 DbResourceForm: Remove default value for host when not required
  application/forms/Config/Resource/DbResourceForm.php
Labels: enhancement

#3652 Auth: do not ask for unrelated group membership
  library/Icinga/Authentication/Auth.php
Labels: bug
