Repository Icinga/icingaweb2, pull requests merged in 2019-06, with the labels that each got.

#3553 Enable `$user:local_name$` placeholder in restrictions
  doc/06-Security.md
  library/Icinga/User.php
Labels: area/authentication, enhancement

#3812 CLI: Fix CSS path
  library/Icinga/Web/StyleSheet.php
Labels: area/cli, bug

#3819 Support relative links with a base path
  application/layouts/scripts/layout.phtml
Labels: area/navigation, enhancement

#3830 Fix object actions dont handle external paths properly
  library/Icinga/Web/Url.php
  modules/monitoring/library/Monitoring/Web/Navigation/Action.php
Labels: area/navigation, bug
