Repository Icinga/icingaweb2, pull requests merged in 2019-12, with the labels that each got.

#4004 Also trim trailing whitespace from search values
  library/Icinga/Web/Widget/FilterEditor.php
Labels: area/navigation, enhancement

#4013 Support for PHP 7.4
  .travis.yml
  application/forms/Config/ResourceConfigForm.php
  application/forms/Config/UserBackendConfigForm.php
  application/forms/Config/UserGroup/UserGroupBackendForm.php
  application/forms/Security/RoleForm.php
  library/Icinga/Application/Web.php
  library/Icinga/Chart/Donut.php
  library/Icinga/Protocol/Ldap/LdapConnection.php
  library/Icinga/Repository/IniRepository.php
  library/Icinga/Util/Format.php
  library/Icinga/Web/Form.php
  library/Icinga/Web/Form/Decorator/FormHints.php
  library/Icinga/Web/View.php
  library/Icinga/Web/ViewStream.php
  library/vendor/HTMLPurifier/ChildDef/Custom.php
  library/vendor/HTMLPurifier/Encoder.php
  library/vendor/HTMLPurifier/TagTransform/Font.php
  library/vendor/Zend/Filter/Compress/Zip.php
  library/vendor/Zend/Json/Decoder.php
  library/vendor/Zend/Json/Encoder.php
  library/vendor/Zend/Registry.php
  library/vendor/Zend/Validate/Isbn.php
  library/vendor/lessphp/lessc.inc.php
  modules/monitoring/application/forms/Setup/IdoResourcePage.php
  modules/monitoring/library/Monitoring/Cli/CliUtils.php
  modules/monitoring/library/Monitoring/MonitoringWizard.php
  modules/setup/application/forms/AuthBackendPage.php
  modules/setup/application/forms/LdapResourcePage.php
  modules/translation/library/Translation/Cli/ArrayToTextTableHelper.php
  test/setup_vendor.sh
Labels: area/installation, enhancement

#4010 Move form colours to the base.less
  public/css/icinga/base.less
  public/css/icinga/forms.less
Labels: area/framework

#3993 Introduce option to hide specific customvars in web
  modules/monitoring/application/forms/Config/SecurityConfigForm.php
  modules/monitoring/library/Monitoring/Object/MonitoredObject.php
Labels: area/authentication, area/monitoring, enhancement

#4014 New permission `no-monitoring/contacts`
  library/Icinga/User.php
  modules/monitoring/application/controllers/ListController.php
  modules/monitoring/application/controllers/ShowController.php
  modules/monitoring/application/views/scripts/partials/object/detail-content.phtml
  modules/monitoring/configuration.php
  modules/monitoring/library/Monitoring/Web/Controller/MonitoredObjectController.php
Labels: area/authentication, area/monitoring, enhancement

#4015 New permission `no-user/password-change`
  application/controllers/AccountController.php
  application/forms/Security/RoleForm.php
Labels: area/authentication, enhancement

#4016 Set `COLLATE 'latin1_general_ci'` for `latin1` charsets on MySQL connections
  library/Icinga/Data/Db/DbConnection.php
Labels: area/framework, bug

#4017 Fix external authentication
  application/views/scripts/navigation/dashboard.phtml
  library/Icinga/Authentication/User/ExternalBackend.php
Labels: area/authentication, bug

#4018 hosts/services: Remove `*_active_checks_enabled` from a redirect's filter
  modules/monitoring/application/controllers/HostsController.php
  modules/monitoring/application/controllers/ServicesController.php
Labels: area/monitoring, bug

#4019 Make toggle sliders accessible
  library/Icinga/Web/View/Helper/IcingaCheckbox.php
  public/css/icinga/forms.less
Labels: area/accessibility, area/ui, bug

#3904 Rework layout with flexbox
  application/layouts/scripts/body.phtml
  application/layouts/scripts/parts/navigation.phtml
  modules/monitoring/application/views/scripts/list/hosts.phtml
  modules/monitoring/application/views/scripts/list/services.phtml
  modules/monitoring/public/css/module.less
  public/css/icinga/layout-structure.less
  public/css/icinga/layout.less
  public/css/icinga/menu.less
  public/css/icinga/responsive.less
  public/css/icinga/setup.less
  public/css/icinga/tabs.less
  public/css/themes/Winter.less
  public/css/themes/solarized-dark.less
  public/js/icinga/behavior/application-state.js
  public/js/icinga/behavior/filtereditor.js
  public/js/icinga/behavior/navigation.js
  public/js/icinga/events.js
  public/js/icinga/loader.js
  public/js/icinga/ui.js
Labels: area/ui, enhancement

#4021 Assist browsers in breaking permission and restriction labels onto multiple lines
  application/forms/Security/RoleForm.php
Labels: area/ui, bug

#4022 Also consider normal acknowledgements for acknowledged problems
  modules/monitoring/configuration.php
Labels: area/monitoring, bug

#4023 Fix that the role form doesn't use config form events
  application/forms/Security/RoleForm.php
  library/Icinga/Application/Hook/ConfigFormEventsHook.php
Labels: area/framework, bug, ref/IP

#4024 Numbers in filter conditions not interpreted correctly
  library/Icinga/Data/Filter/FilterQueryString.php
Labels: bug

#4030 Username with extraneous spaces are not invalid
  library/Icinga/Authentication/User/DbUserBackend.php
Labels: area/authentication, bug

#3970 Refresh container if X-Icinga-Extra-Updates with length 1 is defined
  public/js/icinga/loader.js
Labels: area/framework

#4025 Update Japanese translation
  modules/monitoring/application/locale/ja_JP/LC_MESSAGES/monitoring.mo
  modules/monitoring/application/locale/ja_JP/LC_MESSAGES/monitoring.po
Labels: area/localization, enhancement

#3969 Add custom tab hook
  modules/monitoring/application/views/scripts/object/detail-tabhook.phtml
  modules/monitoring/library/Monitoring/Hook/ObjectDetailsTabHook.php
  modules/monitoring/library/Monitoring/Web/Controller/MonitoredObjectController.php
Labels: area/framework, area/monitoring, enhancement, ref/IP

#3997 Added Kiosk Mode in doc
  doc/20-Advanced-Topics.md
Labels: area/documentation, enhancement

#4032 Trigger config events on enabling/disabling modules
  application/controllers/ConfigController.php
  application/forms/ActionForm.php
Labels: area/configuration, area/framework, enhancement, ref/IP
