Repository Icinga/icingaweb2, pull requests merged in 2019-05, with the labels that each got.

#3304 Integrate DetailviewExtension into multi-select views
  modules/monitoring/application/controllers/HostsController.php
  modules/monitoring/application/controllers/ServicesController.php
  modules/monitoring/application/views/scripts/hosts/show.phtml
  modules/monitoring/application/views/scripts/services/show.phtml
  modules/monitoring/library/Monitoring/Hook/DetailviewExtensionHook.php
  modules/monitoring/library/Monitoring/Web/Controller/MonitoredObjectController.php
Labels: enhancement, monitoring

#3764 Update release docs
  RELEASE.md
Labels: area/documentation

#3655 Setup: Allow to enable FPM
  modules/setup/application/clicommands/ConfigCommand.php
  modules/setup/library/Setup/Webserver.php
  modules/setup/library/Setup/Webserver/Apache.php
  modules/setup/library/Setup/Webserver/Nginx.php
Labels: area/cli, area/configuration, enhancement

#3790 Update documentation to fetch keys securely
  doc/02-Installation.md
Labels: area/documentation

#3743 Add colorblind theme
  doc/01-About.md
  doc/03-Configuration.md
  public/css/themes/colorblind.less
Labels: area/accessibility, enhancement

#3570 Return non-zero on display usage
  library/Icinga/Application/Cli.php
  library/Icinga/Cli/Command.php
Labels: area/cli, enhancement

#3625 icingacli web serve: preserve console colors and avoid redundand process
  application/clicommands/WebCommand.php
Labels: area/cli, enhancement

#3778 Also adjust env var `LANGUAGE` when setting up the locale
  library/Icinga/Util/Translator.php
Labels: area/localization, bug

#3776 Add Japanese language support
  application/locale/ja_JP/LC_MESSAGES/icinga.mo
  application/locale/ja_JP/LC_MESSAGES/icinga.po
  modules/doc/application/locale/ja_JP/LC_MESSAGES/doc.mo
  modules/doc/application/locale/ja_JP/LC_MESSAGES/doc.po
  modules/monitoring/application/locale/ja_JP/LC_MESSAGES/monitoring.mo
  modules/monitoring/application/locale/ja_JP/LC_MESSAGES/monitoring.po
  modules/setup/application/locale/ja_JP/LC_MESSAGES/setup.mo
  modules/setup/application/locale/ja_JP/LC_MESSAGES/setup.po
Labels: area/localization, enhancement

#3779 tests: Don't include non-enabled modules
  modules/test/application/clicommands/PhpCommand.php
Labels: bug

#3766 loader.js: Return in onComplete upon handled redirects
  public/js/icinga/loader.js
Labels: area/javascript, bug

#3792 Multiple announcements broken without javascript
  library/Icinga/Web/Announcement/AnnouncementIniRepository.php
Labels: bug

#3247 Improve Event Grid performance
  modules/monitoring/application/controllers/ListController.php
  modules/monitoring/library/Monitoring/Backend/Ido/Query/EventgridhostsQuery.php
  modules/monitoring/library/Monitoring/Backend/Ido/Query/EventgridservicesQuery.php
  modules/monitoring/library/Monitoring/DataView/Eventgridhosts.php
  modules/monitoring/library/Monitoring/DataView/Eventgridservices.php
Labels: area/monitoring, enhancement

#3775 Improve mobile menu
  public/css/icinga/layout.less
  public/css/icinga/menu.less
  public/css/icinga/responsive.less
  public/js/icinga/ui.js
Labels: area/ui, enhancement

#3723 Make ctrl-click open new tab
  public/js/icinga/behavior/navigation.js
  public/js/icinga/events.js
Labels: area/navigation, enhancement

#3783 Added info about icingaweb endpoint into "System -> Monitoring Health" section
  modules/monitoring/application/views/scripts/health/info.phtml
Labels: area/monitoring, enhancement

#3781 Fixes 2266. Special handling of notification 'output' field.
  modules/monitoring/library/Monitoring/Backend/Ido/Query/HostnotificationQuery.php
  modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicenotificationQuery.php
Labels: area/monitoring, bug

#3794 Allow to fully customize click and submit handling
  public/js/icinga/behavior/actiontable.js
  public/js/icinga/events.js
Labels: area/javascript, enhancement

#3805 Fix the indentation of level-2 nav-items
  public/css/icinga/base.less
  public/css/icinga/menu.less
Labels: area/ui, enhancement
