Repository Icinga/icingaweb2, pull requests merged in 2019-08, with the labels that each got.

#3902 Fix bad looking login form errors
  public/css/icinga/login.less
  public/css/icinga/responsive.less
Labels: area/ui, bug

#3893 Highlight links in monitoring's markdown content
  modules/monitoring/public/css/module.less
Labels: area/monitoring, area/ui, enhancement

#3895 Don't fail dashboard migration just because a locale is missing
  modules/migrate/application/clicommands/DashboardCommand.php
Labels: area/configuration, bug

#3908 Improve high contrast theme readability
  public/css/themes/high-contrast.less
Labels: area/ui, bug

#3903 Support wildcard filters in chains
  library/Icinga/Data/Db/DbQuery.php
Labels: area/framework, bug

#3917 Fix flawed group filter chains
  library/Icinga/Data/Db/DbQuery.php
  modules/monitoring/library/Monitoring/Backend/Ido/Query/HostgroupQuery.php
  modules/monitoring/library/Monitoring/Backend/Ido/Query/IdoQuery.php
  modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicegroupQuery.php
Labels: area/framework, bug

#3919 Center inputs in loginform
  public/css/icinga/login.less
Labels: area/ui, bug
