Repository Icinga/icingaweb2, pull requests merged in 2020-01, with the labels that each got.

#3971 Add EventDetailsExtensionHook and include it into EventController
  modules/monitoring/application/controllers/EventController.php
  modules/monitoring/application/views/scripts/event/show.phtml
  modules/monitoring/library/Monitoring/Hook/EventDetailsExtensionHook.php
Labels: area/framework, area/monitoring, enhancement

#4045 css: Remove left-right padding from inline form elements
  public/css/icinga/forms.less
Labels: area/ui, bug

#4046 Fix error on incomplete ldap inspection
  application/forms/Config/ResourceConfigForm.php
  application/forms/Config/UserBackendConfigForm.php
  application/forms/Config/UserGroup/UserGroupBackendForm.php
  library/Icinga/Protocol/Ldap/LdapConnection.php
Labels: area/configuration, bug

#4044 Fix pdf export error handling
  library/Icinga/File/Pdf.php
  library/Icinga/Web/Controller/ActionController.php
Labels: area/export, bug

#4050 Allow iterable for delete comments and downtimes command forms
  modules/monitoring/application/forms/Command/Object/DeleteCommentsCommandForm.php
  modules/monitoring/application/forms/Command/Object/DeleteDowntimesCommandForm.php
Labels: bug

#4052 Url: Fix @return hints
  library/Icinga/Web/Url.php
Labels: bug

#4051 WebBaseHook: Make setView() fluent
  library/Icinga/Application/Hook/WebBaseHook.php
Labels: bug

#4056 Fix js url param parsing
  public/js/icinga/utils.js
Labels: area/javascript, bug

#4053 JS: Introduce Icinga.Utils.addUrlFlag()
  public/js/icinga/loader.js
  public/js/icinga/utils.js
Labels: area/javascript

#4055 JS: Introduce Icinga.History.replaceCurrentState()
  public/js/icinga/history.js
Labels: area/framework, area/javascript, enhancement

#4048 Fix server side window handling
  library/Icinga/Web/Controller/ActionController.php
  library/Icinga/Web/Request.php
  library/Icinga/Web/Response.php
  library/Icinga/Web/Window.php
Labels: area/framework, bug

#4049 Fix pdfexport hooks may cause bad loading times
  library/Icinga/File/Pdf.php
  library/Icinga/Web/Widget/Tabextension/OutputFormat.php
Labels: area/export, area/framework, bug

#4057 JS: Respect container in Icinga.Ui.focusElement()
  public/js/icinga/ui.js
Labels: area/framework, area/javascript, bug

#4047 Fix Firefox layout issues
  modules/monitoring/public/css/tables.less
  public/css/icinga/tabs.less
Labels: area/ui, bug

#4064 Fix collapsed menu badges
  public/css/icinga/menu.less
Labels: area/ui, bug
