Repository Icinga/icingaweb2, pull requests merged in 2020-11, with the labels that each got.

#4273 list/services: Avoid duplicates when filtering contact(group)s
  modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicestatusQuery.php
Labels: area/monitoring, bug

#4219 Don't try to resolve macros in non existing action urls
  modules/monitoring/library/Monitoring/Web/Navigation/Action.php
Labels: area/navigation, bug

#4275 Fix zero page limit loads everything
  application/forms/PreferenceForm.php
  library/Icinga/Web/Controller.php
Labels: area/configuration, bug

#4277 Fix color shifts in state summary badges
  public/css/icinga/menu.less
Labels: area/ui, bug

#4235 Drop sparkline.js and render inline-pies as SVG
  library/Icinga/Web/JavaScript.php
  library/Icinga/Web/Widget/Chart/InlinePie.php
  modules/monitoring/library/Monitoring/Plugin/Perfdata.php
  modules/monitoring/public/css/module.less
  public/js/icinga/behavior/sparkline.js
  public/js/vendor/jquery.sparkline.js
  public/js/vendor/jquery.sparkline.min.js
Labels: area/framework, bug

#4217 Url::fromPath(): var_export() input value to complain about
  library/Icinga/Web/Url.php
Labels: area/framework

#4272 Add library support
  application/clicommands/ModuleCommand.php
  application/controllers/AboutController.php
  application/controllers/ConfigController.php
  application/controllers/ErrorController.php
  application/views/scripts/about/index.phtml
  application/views/scripts/config/module.phtml
  application/views/scripts/error/error.phtml
  icingaweb2.ruleset.xml
  library/Icinga/Application/ApplicationBootstrap.php
  library/Icinga/Application/Cli.php
  library/Icinga/Application/EmbeddedWeb.php
  library/Icinga/Application/Libraries.php
  library/Icinga/Application/Libraries/Library.php
  library/Icinga/Application/Modules/Manager.php
  library/Icinga/Application/Modules/Module.php
  library/Icinga/Application/StaticWeb.php
  library/Icinga/Application/Web.php
  library/Icinga/Application/webrouter.php
  library/Icinga/Web/Controller/StaticController.php
  library/Icinga/Web/JavaScript.php
  library/Icinga/Web/StyleSheet.php
  modules/setup/library/Setup/Utils/EnableModuleStep.php
  public/css/icinga/about.less
  public/css/icinga/main.less
  public/js/define.js
Labels: affects-upgrades, area/framework, enhancement

#4236 Add notification beads for disabled active checks
  modules/monitoring/library/Monitoring/Web/Navigation/Renderer/BackendAvailabilityNavigationItemRenderer.php
Labels: area/monitoring, enhancement, needs-feedback

#4170 Make auto refresh interval configurable
  application/controllers/ApplicationStateController.php
  application/forms/PreferenceForm.php
  library/Icinga/Web/Controller/ActionController.php
Labels: area/configuration, enhancement
