Repository Icinga/icingaweb2, pull requests merged in 2020-06, with the labels that each got.

#4165 CLI: Also register assets
  library/Icinga/Application/Modules/Module.php
Labels: area/cli, area/framework, bug

#4164 Fix view compact handling
  doc/80-Upgrading.md
  library/Icinga/Web/Controller.php
  library/Icinga/Web/Controller/ActionController.php
  library/Icinga/Web/Url.php
  library/Icinga/Web/Widget/FilterEditor.php
  modules/monitoring/application/controllers/ListController.php
  modules/monitoring/application/controllers/ServicesController.php
  modules/monitoring/application/views/scripts/list/comments.phtml
  modules/monitoring/application/views/scripts/list/contacts.phtml
  modules/monitoring/application/views/scripts/list/downtimes.phtml
  modules/monitoring/application/views/scripts/list/hostgroups.phtml
  modules/monitoring/application/views/scripts/list/hosts.phtml
  modules/monitoring/application/views/scripts/list/notifications.phtml
  modules/monitoring/application/views/scripts/list/servicegroups.phtml
  modules/monitoring/application/views/scripts/list/services.phtml
  modules/monitoring/application/views/scripts/partials/event-history.phtml
  modules/monitoring/application/views/scripts/partials/show-more.phtml
  modules/monitoring/library/Monitoring/DataView/DataView.php
  public/js/icinga/behavior/modal.js
Labels: area/framework

#4168 js: Properly parse/build url query values
  public/js/icinga/utils.js
Labels: area/javascript, bug

#4166 modal.less: Optimize close button styles
  public/css/icinga/modal.less
Labels: area/ui

#4173 css: Fix relative path loading for icinga-loader.gif
  public/css/icinga/base.less
Labels: area/ui, bug

#4179 Fix case insensitive membership filters on Postgres
  modules/monitoring/library/Monitoring/Backend/Ido/Query/IdoQuery.php
Labels: area/monitoring, bug

#4120 Set default IDO charset to latin1
  modules/monitoring/library/Monitoring/Backend/MonitoringBackend.php
Labels: affects-upgrades, area/configuration, area/monitoring, enhancement

#4137 Add ConfigFormEventsHook to UserForm and UserGroupForm
  application/forms/Config/User/UserForm.php
  application/forms/Config/UserGroup/UserGroupForm.php
Labels: area/modules, enhancement

#4190 Show overflowing content in the sidebar while in minimal layout
  public/css/icinga/responsive.less
Labels: area/ui, bug

#4186 Fix that logins are not case-insensitive anymore
  library/Icinga/Authentication/User/DbUserBackend.php
Labels: area/authentication, bug

#4183 Fix timestamp filters in history views
  library/Icinga/Data/Db/DbQuery.php
Labels: area/framework, bug

#4181 Add icons for redesigned paginator
  application/fonts/fontello-ifont/config.json
  application/fonts/fontello-ifont/css/ifont-codes.css
  application/fonts/fontello-ifont/css/ifont-embedded.css
  application/fonts/fontello-ifont/css/ifont-ie7-codes.css
  application/fonts/fontello-ifont/css/ifont-ie7.css
  application/fonts/fontello-ifont/css/ifont.css
  application/fonts/fontello-ifont/demo.html
  application/fonts/fontello-ifont/font/ifont.eot
  application/fonts/fontello-ifont/font/ifont.svg
  application/fonts/fontello-ifont/font/ifont.ttf
  application/fonts/fontello-ifont/font/ifont.woff
  application/fonts/fontello-ifont/font/ifont.woff2
Labels: area/ui
