Repository Icinga/icingaweb2, pull requests merged in 2020-12, with the labels that each got.

#4162 Monitoring: add expire option for comments
  modules/monitoring/application/forms/Command/Object/AddCommentCommandForm.php
  modules/monitoring/application/views/scripts/show/components/comments.phtml
  modules/monitoring/doc/03-Configuration.md
  modules/monitoring/library/Monitoring/Command/Object/AddCommentCommand.php
  modules/monitoring/library/Monitoring/Command/Renderer/IcingaApiCommandRenderer.php
Labels: area/monitoring, enhancement

#4278 Add support for LESS variable exports by modules
  library/Icinga/Web/LessCompiler.php
Labels: area/framework, enhancement

#4265 Shared navigation url bug
  library/Icinga/Web/Url.php
Labels: ref/IP
