Repository Icinga/icingaweb2, pull requests merged in 2020-04, with the labels that each got.

#3926 Add appropriate aria labels to tactical overview
  library/Icinga/Chart/Donut.php
  modules/monitoring/application/views/scripts/tactical/index.phtml
Labels: area/accessibility, enhancement

#4126 Fix tactical overview misinterpreting environment
  modules/monitoring/application/controllers/TacticalController.php
Labels: area/monitoring, bug

#4121 Docs: include Ubuntu in "Preparing Web Setup on Debian"
  doc/02-Installation.md
Labels: area/documentation, area/installation, enhancement

#4008 Form: allow checkboxes to be required
  application/forms/Config/General/ApplicationConfigForm.php
  application/forms/Config/ResourceConfigForm.php
  application/forms/Config/User/UserForm.php
  application/forms/PreferenceForm.php
  library/Icinga/Web/Form.php
  modules/monitoring/application/forms/Config/BackendConfigForm.php
  modules/monitoring/application/forms/Config/TransportConfigForm.php
  modules/setup/application/forms/ModulePage.php
Labels: area/framework, bug

#3964 Show roles of a user
  application/controllers/UserController.php
  application/locale/de_DE/LC_MESSAGES/icinga.mo
  application/locale/de_DE/LC_MESSAGES/icinga.po
  application/views/scripts/user/show.phtml
  public/css/icinga/main.less
Labels: area/ui, enhancement, ref/NC

#4087 Redesign container loading effects
  public/css/icinga/base.less
  public/img/icinga-loader.gif
  public/js/icinga/loader.js
Labels: area/ui, enhancement

#3789 Fix main layout for use without js
  application/forms/Control/LimiterControlForm.php
  library/Icinga/Web/Widget/Dashboard/Dashlet.php
  library/Icinga/Web/Widget/SortBox.php
  modules/monitoring/application/controllers/ListController.php
  public/css/icinga/controls.less
  public/css/icinga/forms.less
  public/css/icinga/layout.less
  public/css/icinga/menu.less
Labels: area/ui, bug

#4134 Icinga.Loader#onFailure(): treat 5xx response as connection failure
  public/js/icinga/loader.js
Labels: area/javascript, bug

#4132 Fix Vagrant provision failure
  .puppet/files/etc/profile.d/env.sh
  .puppet/modules/php/manifests/init.pp
  .puppet/modules/php/manifests/phpd.pp
  .puppet/profiles/icingaweb2_dev/manifests/init.pp
Labels: area/vagrant
