Repository Icinga/icingaweb2, pull requests merged in 2020-02, with the labels that each got.

#4084 Make sure that class container has its container
  public/js/icinga/loader.js
Labels: area/installation, bug

#4085 responsive.less: Do not hide #col2 after reload
  public/css/icinga/responsive.less
  public/js/icinga/history.js
  public/js/icinga/loader.js
Labels: area/ui

#4088 Fix scroll issues in the setup wizard
  modules/setup/application/views/scripts/index/index.phtml
  public/css/icinga/setup.less
Labels: area/ui, bug

#4089 Fix flyouts overlapped by main content
  public/css/icinga/layout-structure.less
Labels: area/ui, bug
