Repository Icinga/icingaweb2, pull requests merged in 2021-05, with the labels that each got.

#4368 doc: Add a note about browser support in the install section
  doc/02-Installation.md
Labels: area/documentation, enhancement

#4371 Pass event instead of object to the getHtmlForEvent method of EventDetailsExtensionHook
  modules/monitoring/application/controllers/EventController.php
  modules/monitoring/library/Monitoring/Hook/EventDetailsExtensionHook.php
Labels: affects-upgrades, area/framework, area/modules, bug

#4373 Cleanup compat stuff
  library/Icinga/Web/JavaScript.php
  public/css/icinga/compat.less
  public/js/vendor/jquery-migrate-3.1.0.js
  public/js/vendor/jquery-migrate-3.1.0.min.js
Labels: affects-upgrades, area/framework, area/javascript

#4355 Health endpoint
  application/controllers/HealthController.php
  library/Icinga/Application/Hook/HealthHook.php
  library/Icinga/Web/Menu.php
  library/Icinga/Web/Navigation/Renderer/HealthNavigationRenderer.php
  library/Icinga/Web/StyleSheet.php
  library/Icinga/Web/View/AppHealth.php
  modules/monitoring/library/Monitoring/ProvidedHook/Health.php
  modules/monitoring/run.php
  public/css/icinga/health.less
Labels: enhancement

#4354 Add datetime picker widget
  application/forms/PreferenceForm.php
  application/layouts/scripts/layout.phtml
  application/views/helpers/FormDateTime.php
  library/Icinga/Authentication/Auth.php
  library/Icinga/Web/JavaScript.php
  public/css/icinga/modal.less
  public/css/themes/solarized-dark.less
  public/js/define.js
  public/js/icinga/behavior/datetime-picker.js
  public/js/icinga/behavior/modal.js
Labels: area/ui, enhancement

#4112 Remember me
  application/controllers/AccountController.php
  application/controllers/ApplicationStateController.php
  application/controllers/AuthenticationController.php
  application/controllers/ManageUserDevicesController.php
  application/controllers/MyDevicesController.php
  application/controllers/NavigationController.php
  application/forms/Authentication/LoginForm.php
  application/forms/Security/RoleForm.php
  etc/schema/mysql-upgrades/2.9.0.sql
  etc/schema/mysql.schema.sql
  etc/schema/pgsql-upgrades/2.9.0.sql
  etc/schema/pgsql.schema.sql
  library/Icinga/Common/Database.php
  library/Icinga/Crypt/AesCrypt.php
  library/Icinga/Web/Cookie.php
  library/Icinga/Web/Menu.php
  library/Icinga/Web/RememberMe.php
  library/Icinga/Web/RememberMeUserDevicesList.php
  library/Icinga/Web/RememberMeUserList.php
  library/Icinga/Web/UserAgent.php
  public/css/icinga/login.less
Labels: affects-upgrades, area/authentication, enhancement

#4380 Use updated default library path
  library/Icinga/Application/ApplicationBootstrap.php
Labels: area/framework
