Repository Icinga/icingaweb2, pull requests merged in 2021-11, with the labels that each got.

#4539 CSS: Adjust application state summary notification design
  public/css/icinga/widgets.less
Labels: bug, area/ui, cla/signed

#4553 Handle non `.js` files in asset/js and non `.css` or `.less` in asset/css folder
  library/Icinga/Application/Libraries/Library.php
Labels: bug, area/framework, cla/signed

#4566 CSS: Optimize notifications layout
  public/css/icinga/widgets.less
Labels: area/ui, cla/signed

#4569 tabs.less: Fix tab dropdown being obscured by object-statistics-total
  public/css/icinga/tabs.less
Labels: cla/signed

#4547 PluginOutput: Don't "optimize" two subsequent newlines to one
  modules/monitoring/application/views/helpers/PluginOutput.php
  modules/monitoring/test/php/application/views/helpers/PluginOutputTest.php
Labels: bug, area/monitoring, ref/NC, cla/signed

#4570 tests: Load external libraries
  test/php/bootstrap.php
Labels: cla/signed

#4580 Fix missing themes cause errors
  application/forms/PreferenceForm.php
  library/Icinga/Web/StyleSheet.php
Labels: bug, area/configuration, cla/signed

#4564 Migrate: Add possibility to migrate monitoring navigation items
  modules/migrate/application/clicommands/NavigationCommand.php
Labels: enhancement, area/navigation, area/monitoring, cla/signed

#4582 Show more helpful less parser errors
  library/Icinga/Web/LessCompiler.php
Labels: area/framework, cla/signed

#4567 Bugfix/mobile issues 4562
  application/forms/PreferenceForm.php
  public/css/icinga/forms.less
  public/css/icinga/layout-structure.less
  public/css/icinga/layout.less
  public/css/icinga/responsive.less
Labels: bug, area/ui, cla/signed

#4584 NavigationCommand: Add license header
  modules/migrate/application/clicommands/NavigationCommand.php
Labels: cla/signed

#4574 Bugfix/theme issues 4565
  public/css/icinga/base.less
  public/css/icinga/menu.less
Labels: bug, area/ui, cla/signed

#4533 js: Fix regression for loading dependent modules for sub-containers
  public/js/icinga.js
  public/js/icinga/events.js
  public/js/icinga/loader.js
Labels: bug, area/javascript, cla/signed

#4590 Error: Add missing `</div>` for `.content` element
  application/views/scripts/error/error.phtml
Labels: bug, area/ui, cla/signed

#4591 base.less: Optmize contrast for `pre` elements
  public/css/icinga/base.less
Labels: area/ui, cla/signed

#4595 Fix unresponsive modal submit buttons in Safari
  public/js/icinga/behavior/modal.js
  public/js/icinga/events.js
Labels: bug, area/javascript, cla/signed

#4575 Add icingadb as OR dependecy where monitoring module is required
  application/views/scripts/config/module.phtml
  library/Icinga/Application/Modules/Manager.php
  library/Icinga/Application/Modules/Module.php
  public/css/icinga/main.less
Labels: area/framework, cla/signed

#4593 Bugfix/fix collapsible bottom fade gradient
  public/css/icinga/base.less
  public/css/icinga/main.less
Labels: area/ui, cla/signed

#4600 js: Fix that redirects into currently empty columns don't work
  public/js/icinga/loader.js
Labels: bug, area/javascript, cla/signed

#4607 Fix TypeError when skipping ldap in setup wizard
  modules/setup/application/forms/LdapDiscoveryPage.php
Labels: cla/signed

#4606 Release 2.9.5
  CHANGELOG.md
  VERSION
  library/Icinga/Application/Version.php
  modules/doc/module.info
  modules/migrate/module.info
  modules/monitoring/module.info
  modules/setup/module.info
  modules/test/module.info
  modules/translation/module.info
Labels: cla/signed

#4605 Vagrant: Puppet: Icinga Web 2: set config database
  .puppet/profiles/icingaweb2_dev/templates/config.ini.erb
Labels: area/vagrant, cla/signed
