Repository Icinga/icingaweb2, pull requests merged in 2021-04, with the labels that each got.

#4343 Accept any character in custom var names
  modules/monitoring/library/Monitoring/Backend/Ido/Query/IdoQuery.php
Labels: area/monitoring, bug

#4336 Audit View
  application/controllers/GroupController.php
  application/controllers/RoleController.php
  application/controllers/UserController.php
  application/forms/Security/RoleForm.php
  library/Icinga/Authentication/AdmissionLoader.php
  library/Icinga/Authentication/Auth.php
  library/Icinga/Authentication/Role.php
  library/Icinga/Web/Controller/AuthBackendController.php
  library/Icinga/Web/StyleSheet.php
  library/Icinga/Web/View/PrivilegeAudit.php
  library/Icinga/Web/Widget/SingleValueSearchControl.php
  public/css/icinga/audit.less
  public/css/icinga/base.less
  public/css/icinga/controls.less
  public/css/icinga/forms.less
  public/css/icinga/main.less
  public/css/icinga/mixins.less
  public/css/icinga/widgets.less
Labels: area/authentication, enhancement

#4345 RoleForm: Highlight set privileges in headers
  application/forms/Security/RoleForm.php
  public/css/icinga/widgets.less
Labels: enhancement

#4344 Docs: Fix automatic install password hash command
  doc/20-Advanced-Topics.md
Labels: area/documentation, bug

#4349 Fix incorrect `ArrayDatasource` order with limit and offset applied
  library/Icinga/Data/DataArray/ArrayDatasource.php
  test/php/library/Icinga/Data/DataArray/ArrayDatasourceTest.php
Labels: area/framework, bug

#4350 Reload Javascript upon module activation/deactivation
  application/controllers/ConfigController.php
Labels: area/framework, enhancement

#4348 Add basic module documentation
  doc/01-About.md
  doc/08-Modules.md
Labels: area/documentation, enhancement

#4351 Don't render missing perfdata values as `0.00`
  modules/monitoring/library/Monitoring/Plugin/Perfdata.php
Labels: area/monitoring, bug

#4352 setup: Skip browser validation when validating a form manually
  modules/monitoring/library/Monitoring/MonitoringWizard.php
  modules/setup/library/Setup/WebWizard.php
Labels: area/installation, bug

#4363 Enhance markdown formatting
  library/Icinga/Web/Helper/Markdown.php
  library/Icinga/Web/Helper/Markdown/LinkTransformer.php
Labels: area/framework
