Repository Icinga/icingaweb2, pull requests merged in 2021-07, with the labels that each got.

#4418 Fix menu hover colors
  public/css/icinga/base.less
  public/css/icinga/compat.less
  public/css/icinga/menu.less
  public/css/themes/Winter.less
  public/css/themes/high-contrast.less
  public/css/themes/solarized-dark.less
Labels: area/ui, bug

#4424 Fix group views not showing all objects with mixed group filters
  modules/monitoring/library/Monitoring/Backend/Ido/Query/HostgroupQuery.php
  modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicegroupQuery.php
Labels: area/authentication, area/monitoring, bug

#4428 Fix that the right column is lost when enabling a module
  application/controllers/ConfigController.php
  library/Icinga/Web/Response.php
  public/js/icinga/loader.js
Labels: area/navigation, bug

#4425 CSS: Make labels wrap in Safari
  public/css/icinga/widgets.less
Labels: area/ui, bug

#4431 monitoring/list/*: Don't apply restrictions in case of `?format=sql`
  modules/monitoring/application/controllers/ListController.php
Labels: area/authentication, bug

#4455 Vagrant: icingaweb2_dev: install icinga-php-{library,thirdparty}
  .puppet/modules/icinga_packages/manifests/init.pp
  .puppet/profiles/icingaweb2_dev/manifests/init.pp
Labels: area/vagrant

#4460 [Docs] Add path to database schema update scripts for Debian/Ubuntu
  doc/80-Upgrading.md
Labels: area/documentation, bug

#4440 Keep structure of nested cvs during protection
  modules/monitoring/library/Monitoring/Object/MonitoredObject.php
Labels: area/monitoring, bug

#4451 user/createmembership: Don't render `user/form.phtml`
  application/controllers/UserController.php
Labels: area/navigation, bug

#4466 Don't open external urls in comments in iFrames
  library/Icinga/Web/Helper/Markdown/LinkTransformer.php
Labels: area/navigation, enhancement

#4467 Only use `PDO::MYSQL_ATTR_INIT_COMMAND` for mysql connections
  library/Icinga/Common/Database.php
Labels: bug

#4473 Define correct grouping rules for contacts and -groups
  modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicestatusQuery.php
Labels: area/monitoring, bug

#4474 Ensure to properly setup table `icingaweb_rememberme` in the wizard
  modules/setup/library/Setup/WebWizard.php
Labels: area/installation, bug

#4478 collapsible.js: Properly setup collapsibles in `onLayoutChange`
  public/js/icinga/behavior/collapsible.js
Labels: area/javascript, bug

#4468 Disable login orb animation and all orbs for themes
  library/Icinga/Web/StyleSheet.php
  public/css/icinga/base.less
  public/css/icinga/login-orbs.less
  public/css/icinga/login.less
  public/css/icinga/mixins.less
  public/css/themes/solarized-dark.less
  public/img/icingaweb2-background-orbs.jpg
Labels: area/ui, bug

#4477 Fix that the datetime picker doesn't close automatically
  public/js/icinga/behavior/datetime-picker.js
Labels: area/javascript, bug

#4480 Let SVG chart library process input as UTF-8
  library/Icinga/Chart/SVGRenderer.php
Labels: area/framework, bug

#4479 Add preference migration command
  doc/80-Upgrading.md
  modules/migrate/application/clicommands/PreferencesCommand.php
Labels: affects-upgrades, area/cli

#4484 Enforce charset on internal db queries
  library/Icinga/Authentication/User/UserBackend.php
  library/Icinga/Authentication/UserGroup/UserGroupBackend.php
  library/Icinga/Common/Database.php
  library/Icinga/User/Preferences/PreferencesStore.php
  modules/migrate/application/clicommands/PreferencesCommand.php
  modules/migrate/library/Migrate/Config/UserDomainMigration.php
Labels: area/configuration, bug

#4472 Rememberme compatibility with php version 5.6+
  application/controllers/AuthenticationController.php
  application/controllers/ManageUserDevicesController.php
  application/controllers/MyDevicesController.php
  etc/schema/mysql-upgrades/2.9.1.sql
  etc/schema/mysql.schema.sql
  etc/schema/pgsql-upgrades/2.9.1.sql
  etc/schema/pgsql.schema.sql
  library/Icinga/Crypt/AesCrypt.php
  library/Icinga/Web/RememberMe.php
  library/Icinga/Web/RememberMeUserDevicesList.php
  library/Icinga/Web/RememberMeUserList.php
Labels: bug

#4483 Only use Flatpickr for non-native inputs
  public/js/icinga/behavior/datetime-picker.js
Labels: area/javascript

#4487 Make sure to grant general module access if full access is granted
  application/forms/Security/RoleForm.php
Labels: area/configuration, bug

#4491 If enforcing a charset, DO IT ONLY IF THE DB TYPE IS CORRECT
  library/Icinga/Authentication/User/UserBackend.php
  library/Icinga/Authentication/UserGroup/UserGroupBackend.php
  library/Icinga/Common/Database.php
  library/Icinga/User/Preferences/PreferencesStore.php
  modules/migrate/application/clicommands/PreferencesCommand.php
  modules/migrate/library/Migrate/Config/UserDomainMigration.php
Labels: bug, queue/important
