Repository Icinga/icingaweb2, pull requests merged in 2021-12, with the labels that each got.

#4616 Fix migrating navigation items only for the given user doesn't work
  modules/migrate/application/clicommands/NavigationCommand.php
Labels: bug, cla/signed

#4623 RoleForm: Really only show that everything is allowed if `*` is granted
  application/forms/Security/RoleForm.php
Labels: bug, area/configuration, cla/signed

#4621 datetime-picker.js: Support input groups
  public/js/icinga/behavior/datetime-picker.js
Labels: area/javascript, area/framework, cla/signed

#4620 Form styles for file inputs and buttons
  public/css/icinga/forms.less
Labels: area/framework, area/ui, cla/signed

#4498 /monitoring/tactical: fall back to unknown services if none critical
  library/Icinga/Chart/Donut.php
  modules/monitoring/application/controllers/TacticalController.php
  public/css/icinga/widgets.less
Labels: enhancement, area/monitoring, cla/signed
