Repository Icinga/icingaweb2, pull requests merged in 2021-06, with the labels that each got.

#4376 Utilize ipl-i18n
  .github/workflows/php.yml
  application/forms/PreferenceForm.php
  application/layouts/scripts/external-logout.phtml
  application/layouts/scripts/layout.phtml
  library/Icinga/Application/ApplicationBootstrap.php
  library/Icinga/Application/Cli.php
  library/Icinga/Application/EmbeddedWeb.php
  library/Icinga/Application/Modules/Module.php
  library/Icinga/Application/Web.php
  library/Icinga/Application/functions.php
  library/Icinga/Cli/Command.php
  library/Icinga/Test/BaseTestCase.php
  library/Icinga/Util/Translator.php
  library/Icinga/Web/Controller/ActionController.php
  library/Icinga/Web/Form.php
  library/Icinga/Web/View.php
  modules/migrate/application/clicommands/DashboardCommand.php
  modules/translation/application/clicommands/CompileCommand.php
  modules/translation/application/clicommands/RefreshCommand.php
  modules/translation/application/clicommands/TestCommand.php
  modules/translation/doc/03-Translation.md
  modules/translation/library/Translation/Util/GettextTranslationHelper.php
  modules/translation/module.info
  test/php/library/Icinga/Util/TranslatorTest.php
  test/php/regression/Bug6432Test.php
  test/php/res/locale/de_DE/LC_MESSAGES/icingatest.mo
  test/php/res/locale/de_DE/LC_MESSAGES/icingatest.po
  test/php/res/locale/fr_FR/LC_MESSAGES/icingatest.mo
  test/php/res/locale/fr_FR/LC_MESSAGES/icingatest.po
Labels: area/localization, enhancement

#4382 Module: Allow `/` and `-` in module/library dependency names
  library/Icinga/Application/Modules/Module.php
Labels: area/framework

#4381 Fully integrate ipl as dependency
  application/controllers/ErrorController.php
  application/views/scripts/error/error.phtml
  doc/02-Installation.md
  library/Icinga/Application/Libraries/Library.php
  public/css/icinga/main.less
Labels: area/framework

#4393 Make configuration of custom user backends possible
  application/forms/Config/UserBackendConfigForm.php
  library/Icinga/Authentication/User/UserBackend.php
  library/Icinga/Authentication/User/UserBackendInterface.php
  test/php/application/forms/Config/UserBackendReorderFormTest.php
Labels: area/framework, enhancement

#4388 Make configuration of custom user-group backends possible
  application/forms/Config/UserGroup/UserGroupBackendForm.php
  library/Icinga/Authentication/UserGroup/UserGroupBackend.php
  library/Icinga/Authentication/UserGroup/UserGroupBackendInterface.php
Labels: area/framework, enhancement

#4391 Improve cache handling
  application/controllers/ConfigController.php
  library/Icinga/Web/JavaScript.php
  library/Icinga/Web/StyleSheet.php
  public/js/icinga/ui.js
Labels: enhancement

#4392 Add end time and comment options to settings section for host/service downtime dialog
  modules/monitoring/application/forms/Command/Object/ScheduleHostDowntimeCommandForm.php
  modules/monitoring/application/forms/Command/Object/ScheduleServiceDowntimeCommandForm.php
  modules/monitoring/doc/03-Configuration.md
Labels: area/configuration, area/monitoring, enhancement

#4397 Raise minimum required PHP version to 7.3
  doc/02-Installation.md
  doc/80-Upgrading.md
  modules/setup/library/Setup/WebWizard.php
Labels: affects-upgrades

#4337 Feature/icinga dark theme login
  application/forms/Authentication/LoginForm.php
  application/layouts/scripts/body.phtml
  application/views/scripts/about/index.phtml
  application/views/scripts/authentication/login.phtml
  modules/monitoring/application/views/scripts/show/contact.phtml
  modules/monitoring/public/css/module.less
  public/css/icinga/badges.less
  public/css/icinga/base.less
  public/css/icinga/controls.less
  public/css/icinga/forms.less
  public/css/icinga/layout-structure.less
  public/css/icinga/layout.less
  public/css/icinga/login.less
  public/css/icinga/main.less
  public/css/icinga/menu.less
  public/css/icinga/responsive.less
  public/css/icinga/setup.less
  public/css/icinga/tabs.less
  public/css/themes/colorblind.less
  public/css/themes/high-contrast.less
  public/css/themes/icinga-light-theme.less
  public/img/icinga-loader-light.gif
  public/img/icinga-loader.gif
  public/img/icinga-logo-compact-inverted.svg
  public/img/icinga-logo-inverted.svg
  public/img/icingaweb2-background-orbs.jpg
  public/img/orb-analytics.png
  public/img/orb-automation.png
  public/img/orb-cloud.png
  public/img/orb-icinga.png
  public/img/orb-infrastructure.png
  public/img/orb-metrics.png
  public/img/orb-notifications.png
  public/img/select-icon-2x.png
  public/img/select-icon.png
  public/img/select-icon.svg
Labels: area/ui, enhancement

#4398 Integrate light theme as mode in default theme
  library/Icinga/Util/LessParser.php
  modules/doc/public/css/module.less
  modules/monitoring/public/css/module.less
  modules/monitoring/public/css/service-grid.less
  modules/monitoring/public/css/tables.less
  public/css/icinga/about.less
  public/css/icinga/audit.less
  public/css/icinga/badges.less
  public/css/icinga/base.less
  public/css/icinga/controls.less
  public/css/icinga/forms.less
  public/css/icinga/health.less
  public/css/icinga/layout.less
  public/css/icinga/login.less
  public/css/icinga/main.less
  public/css/icinga/menu.less
  public/css/icinga/mixins.less
  public/css/icinga/modal.less
  public/css/icinga/responsive.less
  public/css/icinga/setup.less
  public/css/icinga/tabs.less
  public/css/icinga/widgets.less
  public/css/themes/icinga-light-theme.less
Labels: area/ui

#4399 Document use_ssl database resource config option
  doc/04-Resources.md
Labels: area/documentation

#4402 Respect yet unused CSS variables as well
  modules/doc/public/css/module.less
  modules/monitoring/public/css/module.less
  modules/monitoring/public/css/service-grid.less
  modules/monitoring/public/css/tables.less
  public/css/icinga/about.less
  public/css/icinga/audit.less
  public/css/icinga/base.less
  public/css/icinga/controls.less
  public/css/icinga/forms.less
  public/css/icinga/health.less
  public/css/icinga/layout.less
  public/css/icinga/login.less
  public/css/icinga/main.less
  public/css/icinga/menu.less
  public/css/icinga/mixins.less
  public/css/icinga/setup.less
  public/css/icinga/widgets.less
Labels: area/ui, enhancement

#4400 Support $user.local_name$ macro in navigation items
  doc/06-Security.md
  doc/80-Upgrading.md
  library/Icinga/Authentication/AdmissionLoader.php
  library/Icinga/Web/Navigation/NavigationItem.php
Labels: area/navigation, enhancement, ref/NC

#4410 Fix wizard
  library/Icinga/Web/Wizard.php
  modules/monitoring/library/Monitoring/MonitoringWizard.php
  modules/setup/application/views/scripts/index/parts/finish.phtml
  modules/setup/library/Setup/Utils/DbTool.php
  public/css/icinga/setup.less
Labels: area/installation
