Repository Icinga/icingaweb2, pull requests merged in 2022-07, with the labels that each got.

#4854 Fix incorrect history time and date
  library/Icinga/Data/Db/DbQuery.php
  modules/monitoring/library/Monitoring/Backend/Ido/Query/HostcommentdeletionhistoryQuery.php
  modules/monitoring/library/Monitoring/Backend/Ido/Query/HostcommenthistoryQuery.php
  modules/monitoring/library/Monitoring/Backend/Ido/Query/HostdowntimeendhistoryQuery.php
  modules/monitoring/library/Monitoring/Backend/Ido/Query/HostdowntimestarthistoryQuery.php
  modules/monitoring/library/Monitoring/Backend/Ido/Query/HostflappingstarthistoryQuery.php
  modules/monitoring/library/Monitoring/Backend/Ido/Query/HostnotificationQuery.php
  modules/monitoring/library/Monitoring/Backend/Ido/Query/HoststatehistoryQuery.php
  modules/monitoring/library/Monitoring/Backend/Ido/Query/IdoQuery.php
  modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicecommentdeletionhistoryQuery.php
  modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicecommenthistoryQuery.php
  modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicedowntimeendhistoryQuery.php
  modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicedowntimestarthistoryQuery.php
  modules/monitoring/library/Monitoring/Backend/Ido/Query/ServiceflappingstarthistoryQuery.php
  modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicenotificationQuery.php
  modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicestatehistoryQuery.php
Labels: bug, queue/important, area/monitoring, cla/signed

#4868 Format.php: Handle null values
  library/Icinga/Util/Format.php
Labels: bug, cla/signed

#4810 Align button icon to baseline
  public/css/icinga/mixins.less
Labels: enhancement, area/framework, area/ui, cla/signed

#4822 setup.less: Make visible that the button is disabled
  public/css/icinga/setup.less
Labels: bug, area/ui, cla/signed
