Repository Icinga/icingaweb2, pull requests merged in 2022-04, with the labels that each got.

#4743 CSS: Improve sidebar contrast
  public/css/icinga/base.less
Labels: bug, area/ui, cla/signed

#4698 Set modal title from response header on auto/formsubmit
  library/Icinga/Web/Controller/ActionController.php
  public/js/icinga/behavior/modal.js
Labels: area/javascript, area/framework, cla/signed

#4746 PreferenceForm: Always enable mode selection if user theme is compatible
  application/forms/PreferenceForm.php
Labels: bug, cla/signed

#4669 Fix typo
  library/Icinga/Protocol/Ldap/LdapUtils.php
Labels: cla/signed

#4761 Prevent use of empty filters in FilterChain::toQueryString()
  library/Icinga/Data/Filter/FilterChain.php
Labels: bug, area/navigation, cla/signed
