Repository Icinga/icingaweb2, pull requests merged in 2022-06, with the labels that each got.

#4808 Avoid passing null as hastack to `strpos` in library/vendor/Zend/Form::_dissolveArrayValue()
  library/vendor/Zend/Form.php
Labels: cla/signed

#4799 Fix PHP 8.1 deprecation errors
  library/Icinga/Chart/Unit/LinearUnit.php
  library/Icinga/Web/Form.php
Labels: cla/signed

#4805 Manager: Ensure enableModule dir has correct permission when created
  library/Icinga/Application/Modules/Manager.php
Labels: bug, cla/signed

#4776 overrides `customvarsWithOriginalNames` only if the given object is of type `host`
  modules/monitoring/library/Monitoring/Object/MonitoredObject.php
Labels: bug, area/monitoring, cla/signed

#4814 DbConnection: Only ignore the `*` for equal/unequal conditions
  library/Icinga/Data/Db/DbConnection.php
Labels: bug, cla/signed

#4815 Fix that the audit view doesn't suggest users from domain-aware backends correctly
  application/controllers/RoleController.php
Labels: bug, cla/signed

#4763 Drop IE support
  application/layouts/scripts/external-logout.phtml
  application/layouts/scripts/layout.phtml
  application/layouts/scripts/wrapped.phtml
  doc/02-Installation.md
  doc/80-Upgrading.md
  library/Icinga/Application/webrouter.php
  library/Icinga/Util/LessParser.php
  library/Icinga/Web/Form.php
  library/Icinga/Web/JavaScript.php
  library/Icinga/Web/LessCompiler.php
  library/Icinga/Web/StyleSheet.php
  public/css/icinga/layout-structure.less
  public/css/icinga/main.less
  public/css/icinga/menu.less
  public/css/icinga/mixins.less
  public/js/helpers.js
  public/js/icinga/behavior/actiontable.js
  public/js/icinga/behavior/collapsible.js
  public/js/icinga/behavior/input-enrichment.js
  public/js/icinga/storage.js
Labels: cla/signed

#4812 Stylesheet: Don't parse library CSS as LESS
  library/Icinga/Web/StyleSheet.php
Labels: bug, area/framework, cla/signed

#4820 Stylesheet: Don't parse library CSS as LESS
  library/Icinga/Web/StyleSheet.php
Labels: bug, area/framework, cla/signed

#4821 Stylesheet: Don't parse library CSS as LESS
  library/Icinga/Web/StyleSheet.php
Labels: bug, area/framework, cla/signed

#4752 history.js: Properly handle data attributes upon navigation
  public/js/icinga/history.js
  public/js/icinga/ui.js
Labels: enhancement, area/javascript, cla/signed

#4825 ConfigMenu: Add missing application_log entry
  library/Icinga/Web/Navigation/ConfigMenu.php
Labels: bug, cla/signed

#4823 Fix that the new user menu forgets active states
  library/Icinga/Web/Navigation/ConfigMenu.php
  public/js/icinga/behavior/navigation.js
Labels: bug, area/javascript, cla/signed

#4806 Update 03-Configuration.md: Missing setting "hostdowntime_all_services"
  modules/monitoring/doc/03-Configuration.md
Labels: bug, area/monitoring, area/documentation, cla/signed

#4838 Update docs
  doc/02-Installation.md
Labels: area/documentation, cla/signed

#4831 Fix that navbar forgets active state after refresh
  library/Icinga/Web/Navigation/ConfigMenu.php
  public/js/icinga/behavior/navigation.js
Labels: bug, area/javascript, cla/signed

#4839 Remove legacy search request handling
  public/js/icinga/loader.js
Labels: bug, area/javascript, cla/signed

#4835 Fix light mode variable references resolution issue
  library/Icinga/Less/Call.php
  library/Icinga/Less/ColorProp.php
  library/Icinga/Less/ColorPropOrVariable.php
  library/Icinga/Less/DeferredColorProp.php
  library/Icinga/Less/LightMode.php
  library/Icinga/Less/LightModeCall.php
  library/Icinga/Less/LightModeDefinition.php
  library/Icinga/Less/LightModeTrait.php
  library/Icinga/Less/LightModeVisitor.php
  library/Icinga/Less/Visitor.php
  test/php/library/Icinga/Util/LessParserTest.php
Labels: bug, area/ui, cla/signed

#4846 Fix light mode variable references resolution issue
  library/Icinga/Less/Call.php
  library/Icinga/Less/ColorProp.php
  library/Icinga/Less/ColorPropOrVariable.php
  library/Icinga/Less/DeferredColorProp.php
  library/Icinga/Less/LightMode.php
  library/Icinga/Less/LightModeCall.php
  library/Icinga/Less/LightModeDefinition.php
  library/Icinga/Less/LightModeTrait.php
  library/Icinga/Less/LightModeVisitor.php
  library/Icinga/Less/Visitor.php
  test/php/library/Icinga/Util/LessParserTest.php
Labels: bug, cla/signed

#4841 Introduce schema table
  etc/schema/mysql-upgrades/2.11.0.sql
  etc/schema/mysql.schema.sql
  etc/schema/pgsql-upgrades/2.11.0.sql
  etc/schema/pgsql.schema.sql
Labels: enhancement, cla/signed

#4826 Release v2.11.0
  .mailmap
  AUTHORS
  CHANGELOG.md
  VERSION
  doc/80-Upgrading.md
  library/Icinga/Application/Version.php
  modules/doc/module.info
  modules/migrate/module.info
  modules/monitoring/module.info
  modules/setup/module.info
  modules/test/module.info
  modules/translation/module.info
Labels: cla/signed
