Repository Icinga/icingaweb2, pull requests merged in 2022-02, with the labels that each got.

#4647 Remove module asset support
  doc/80-Upgrading.md
  library/Icinga/Application/Modules/Module.php
  library/Icinga/Web/JavaScript.php
  library/Icinga/Web/LessCompiler.php
  library/Icinga/Web/StyleSheet.php
Labels: affects-upgrades, cla/signed

#4624 Drop locales
  application/locale/ar_SA/LC_MESSAGES/icinga.mo
  application/locale/ar_SA/LC_MESSAGES/icinga.po
  application/locale/de_DE/LC_MESSAGES/icinga.mo
  application/locale/de_DE/LC_MESSAGES/icinga.po
  application/locale/fi_FI/LC_MESSAGES/icinga.mo
  application/locale/fi_FI/LC_MESSAGES/icinga.po
  application/locale/it_IT/LC_MESSAGES/icinga.mo
  application/locale/it_IT/LC_MESSAGES/icinga.po
  application/locale/ja_JP/LC_MESSAGES/icinga.mo
  application/locale/ja_JP/LC_MESSAGES/icinga.po
  application/locale/pt_BR/LC_MESSAGES/icinga.mo
  application/locale/pt_BR/LC_MESSAGES/icinga.po
  application/locale/ru_RU/LC_MESSAGES/icinga.mo
  application/locale/ru_RU/LC_MESSAGES/icinga.po
  application/locale/uk_UA/LC_MESSAGES/icinga.mo
  application/locale/uk_UA/LC_MESSAGES/icinga.po
  library/Icinga/Application/ApplicationBootstrap.php
  modules/doc/application/locale/de_DE/LC_MESSAGES/doc.mo
  modules/doc/application/locale/de_DE/LC_MESSAGES/doc.po
  modules/doc/application/locale/ja_JP/LC_MESSAGES/doc.mo
  modules/doc/application/locale/ja_JP/LC_MESSAGES/doc.po
  modules/doc/application/locale/uk_UA/LC_MESSAGES/doc.mo
  modules/doc/application/locale/uk_UA/LC_MESSAGES/doc.po
  modules/monitoring/application/locale/ar_SA/LC_MESSAGES/monitoring.mo
  modules/monitoring/application/locale/ar_SA/LC_MESSAGES/monitoring.po
  modules/monitoring/application/locale/de_DE/LC_MESSAGES/monitoring.mo
  modules/monitoring/application/locale/de_DE/LC_MESSAGES/monitoring.po
  modules/monitoring/application/locale/it_IT/LC_MESSAGES/monitoring.mo
  modules/monitoring/application/locale/it_IT/LC_MESSAGES/monitoring.po
  modules/monitoring/application/locale/ja_JP/LC_MESSAGES/monitoring.mo
  modules/monitoring/application/locale/ja_JP/LC_MESSAGES/monitoring.po
  modules/monitoring/application/locale/pt_BR/LC_MESSAGES/monitoring.mo
  modules/monitoring/application/locale/pt_BR/LC_MESSAGES/monitoring.po
  modules/monitoring/application/locale/ru_RU/LC_MESSAGES/monitoring.po
  modules/monitoring/application/locale/uk_UA/LC_MESSAGES/monitoring.mo
  modules/monitoring/application/locale/uk_UA/LC_MESSAGES/monitoring.po
  modules/setup/application/locale/de_DE/LC_MESSAGES/setup.mo
  modules/setup/application/locale/de_DE/LC_MESSAGES/setup.po
  modules/setup/application/locale/it_IT/LC_MESSAGES/setup.mo
  modules/setup/application/locale/it_IT/LC_MESSAGES/setup.po
  modules/setup/application/locale/ja_JP/LC_MESSAGES/setup.mo
  modules/setup/application/locale/ja_JP/LC_MESSAGES/setup.po
  modules/setup/application/locale/uk_UA/LC_MESSAGES/setup.mo
  modules/setup/application/locale/uk_UA/LC_MESSAGES/setup.po
  modules/translation/doc/03-Translation.md
Labels: cla/signed

#4654 Do not load any user links in iframes
  library/Icinga/Web/Helper/Markdown/LinkTransformer.php
Labels: bug, area/navigation, cla/signed

#4653 Fix module dependency evaluation
  library/Icinga/Application/Modules/Manager.php
  library/Icinga/Application/Modules/Module.php
Labels: bug, area/modules, cla/signed

#4655 Fix duplicate ids in html
  library/Icinga/Web/Form.php
  library/Icinga/Web/Form/Element/CsrfCounterMeasure.php
  modules/monitoring/application/views/scripts/partials/object/quick-actions.phtml
  public/js/icinga/utils.js
Labels: bug, area/framework, cla/signed

#4656 Properly reset container ids when moving content
  public/js/icinga/ui.js
Labels: bug, area/javascript, cla/signed

#4657 Fix always running behaviors
  doc/80-Upgrading.md
  library/Icinga/Web/JavaScript.php
  public/css/icinga/widgets.less
  public/js/icinga/behavior/actiontable.js
  public/js/icinga/behavior/application-state.js
  public/js/icinga/behavior/collapsible.js
  public/js/icinga/behavior/datetime-picker.js
  public/js/icinga/behavior/expandable.js
  public/js/icinga/behavior/filtereditor.js
  public/js/icinga/behavior/flyover.js
  public/js/icinga/behavior/input-enrichment.js
Labels: bug, area/javascript, affects-upgrades, cla/signed

#4658 Fix ghost columns upon comment removal
  modules/monitoring/application/views/scripts/show/components/comments.phtml
  public/css/icinga/main.less
Labels: bug, area/navigation, area/monitoring, cla/signed

#4659 monitoring/list/hosts: Apply restrictions to host service problem summary
  modules/monitoring/application/controllers/ListController.php
Labels: bug, area/authentication, area/monitoring, cla/signed

#4613 Replace compiled Less colors with CSS var() function calls and generate light mode calls
  library/Icinga/Application/webrouter.php
  library/Icinga/Less/ColorProp.php
  library/Icinga/Less/ColorPropOrVariable.php
  library/Icinga/Less/LightMode.php
  library/Icinga/Less/LightModeCall.php
  library/Icinga/Less/LightModeDefinition.php
  library/Icinga/Less/LightModeTrait.php
  library/Icinga/Less/LightModeVisitor.php
  library/Icinga/Less/Visitor.php
  library/Icinga/Util/LessParser.php
  library/Icinga/Web/LessCompiler.php
  library/Icinga/Web/StyleSheet.php
  test/php/library/Icinga/Util/LessParserTest.php
Labels: area/framework, cla/signed

#4664 Cleanup var mixin usages
  doc/80-Upgrading.md
  library/Icinga/Util/LessParser.php
  library/Icinga/Web/LessCompiler.php
  modules/doc/public/css/module.less
  modules/monitoring/public/css/module.less
  modules/monitoring/public/css/service-grid.less
  modules/monitoring/public/css/tables.less
  public/css/icinga/about.less
  public/css/icinga/audit.less
  public/css/icinga/badges.less
  public/css/icinga/base.less
  public/css/icinga/controls.less
  public/css/icinga/forms.less
  public/css/icinga/health.less
  public/css/icinga/layout.less
  public/css/icinga/login.less
  public/css/icinga/main.less
  public/css/icinga/menu.less
  public/css/icinga/mixins.less
  public/css/icinga/modal.less
  public/css/icinga/responsive.less
  public/css/icinga/setup.less
  public/css/icinga/tabs.less
  public/css/icinga/widgets.less
Labels: area/framework, cla/signed

#4668 Fix that daylight savings are not accounted for in queries
  library/Icinga/Data/Db/DbQuery.php
Labels: bug, area/framework, cla/signed

#4556 Remove mixins that exist in ipl-web
  public/css/icinga/mixins.less
Labels: cla/signed

#4670 Winter.less: Update styles
  public/css/themes/Winter.less
Labels: bug, area/ui, cla/signed

#4671 IdoQuery: Don't try to add a `HAVING` without group by rules
  modules/monitoring/library/Monitoring/Backend/Ido/Query/IdoQuery.php
Labels: bug, area/framework, cla/signed

#4676 Fix that the sidebar shadow narrows the interaction area
  public/css/icinga/layout-structure.less
Labels: bug, area/ui, cla/signed

#4677 Update installation instructions for easier navigation on icinga.com
  doc/02-Installation.md
  doc/02-Installation.md.d/01-Debian.md
  doc/02-Installation.md.d/02-Ubuntu.md
  doc/02-Installation.md.d/03-CentOS.md
  doc/02-Installation.md.d/04-RHEL.md
  doc/02-Installation.md.d/05-SLES.md
  doc/02-Installation.md.d/06-Amazon-Linux.md
  doc/02-Installation.md.d/07-From-Source.md
  doc/20-Advanced-Topics.md
Labels: enhancement, area/documentation, cla/signed

#4496 Feature/redesign about view
  application/views/scripts/about/index.phtml
  library/Icinga/Application/Version.php
  public/css/icinga/about.less
Labels: enhancement, area/ui, cla/signed

#4683 about.less: color “configure” links in about view
  public/css/icinga/about.less
Labels: cla/signed

#4684 Perfdata: Render unknown UOMs as-is
  modules/monitoring/library/Monitoring/Plugin/Perfdata.php
Labels: bug, area/monitoring, cla/signed

#4660 Drop the unhandled services counter in host lists
  modules/monitoring/application/controllers/ListController.php
  modules/monitoring/application/views/scripts/list/hosts.phtml
  modules/monitoring/library/Monitoring/Backend/Ido/Query/HostserviceproblemsummaryQuery.php
  modules/monitoring/library/Monitoring/Backend/Ido/Query/HoststatusQuery.php
  modules/monitoring/public/css/tables.less
Labels: bug, area/monitoring, cla/signed
