Repository Icinga/icingaweb2, pull requests merged in 2022-12, with the labels that each got.

#4949 SshResourceForm: fix XSS by escaping user-defined resource name
  application/forms/Config/Resource/SshResourceForm.php
Labels: bug, cla/signed

#4952 login: Don't redirect to external resources
  application/controllers/AuthenticationController.php
  application/forms/Authentication/LoginForm.php
Labels: bug, area/authentication, cla/signed

#4954 RoleController: Always perform a permission check
  application/controllers/RoleController.php
Labels: bug, area/configuration, cla/signed

#4955 External URLs still allowed in dashlets
  library/Icinga/Web/Form/Validator/InternalUrlValidator.php
Labels: bug, area/configuration, cla/signed

#4943 form.js: Don't ignore autosubmit elements
  public/js/icinga/behavior/form.js
Labels: bug, area/javascript, cla/signed

#4956 ConfigMenu: Fix incorrect shared navigation url
  library/Icinga/Web/Navigation/ConfigMenu.php
Labels: bug, area/navigation, cla/signed

#4958 Fix browser print dialog result
  library/Icinga/Less/Visitor.php
  public/css/icinga/print.less
  test/php/library/Icinga/Util/LessParserTest.php
Labels: bug, area/export, cla/signed

#4941 icingacli test php unit: pass through phpunit exit code
  modules/test/application/clicommands/PhpCommand.php
Labels: cla/signed

#4965 css: Support fieldsets wrapped by `.control-group`
  public/css/icinga/forms.less
Labels: cla/signed
