Repository Icinga/icingaweb2, pull requests merged in 2022-05, with the labels that each got.

#4766 sql: Change charset to `utf8mb4`
  doc/80-Upgrading.md
  etc/schema/mysql-upgrades/2.11.0.sql
  etc/schema/mysql.schema.sql
  library/Icinga/Authentication/User/DbUserBackend.php
  library/Icinga/Authentication/User/UserBackend.php
  library/Icinga/Authentication/UserGroup/DbUserGroupBackend.php
  library/Icinga/Authentication/UserGroup/UserGroupBackend.php
  library/Icinga/User/Preferences/PreferencesStore.php
  modules/migrate/application/clicommands/PreferencesCommand.php
  modules/migrate/library/Migrate/Config/UserDomainMigration.php
Labels: affects-upgrades, cla/signed

#4769 Fix setup wizard
  modules/setup/application/views/scripts/index/index.phtml
  modules/setup/library/Setup/RequirementSet.php
Labels: bug, area/installation, cla/signed

#4773 modal.js: Fix modal hide error
  public/js/icinga/behavior/modal.js
Labels: bug, area/javascript, cla/signed

#4783 ActionController: Don't override reload rules in `redirectXhr()`
  library/Icinga/Web/Controller/ActionController.php
Labels: cla/signed

#4784 Theme loader hook
  library/Icinga/Application/Hook/ThemeLoaderHook.php
  library/Icinga/Web/StyleSheet.php
Labels: cla/signed

#4777 Fix: Scheme and hostname prepended to col2 url in the address bar
  public/js/icinga/loader.js
Labels: bug, area/javascript, cla/signed

#4768 Change FilterMatch to FilterEqual class for single object filter on object name.
  library/Icinga/Data/Db/DbConnection.php
  modules/monitoring/application/controllers/ShowController.php
  modules/monitoring/library/Monitoring/Backend/Ido/Query/CommentQuery.php
  modules/monitoring/library/Monitoring/Backend/Ido/Query/CommentdeletionhistoryQuery.php
  modules/monitoring/library/Monitoring/Backend/Ido/Query/CommenthistoryQuery.php
  modules/monitoring/library/Monitoring/Backend/Ido/Query/ContactQuery.php
  modules/monitoring/library/Monitoring/Backend/Ido/Query/CustomvarQuery.php
  modules/monitoring/library/Monitoring/Backend/Ido/Query/DowntimeQuery.php
  modules/monitoring/library/Monitoring/Backend/Ido/Query/DowntimeendhistoryQuery.php
  modules/monitoring/library/Monitoring/Backend/Ido/Query/DowntimestarthistoryQuery.php
  modules/monitoring/library/Monitoring/Backend/Ido/Query/EventhistoryQuery.php
  modules/monitoring/library/Monitoring/Backend/Ido/Query/FlappingstarthistoryQuery.php
  modules/monitoring/library/Monitoring/Backend/Ido/Query/HoststatussummaryQuery.php
  modules/monitoring/library/Monitoring/Backend/Ido/Query/IdoQuery.php
  modules/monitoring/library/Monitoring/Backend/Ido/Query/NotificationQuery.php
  modules/monitoring/library/Monitoring/Backend/Ido/Query/NotificationhistoryQuery.php
  modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicestatussummaryQuery.php
  modules/monitoring/library/Monitoring/Backend/Ido/Query/StatehistoryQuery.php
  modules/monitoring/library/Monitoring/Backend/Ido/Query/StatussummaryQuery.php
  modules/monitoring/library/Monitoring/DataView/DataView.php
  modules/monitoring/library/Monitoring/Object/Host.php
  modules/monitoring/library/Monitoring/Object/MonitoredObject.php
  modules/monitoring/library/Monitoring/Object/Service.php
Labels: bug, area/framework, area/monitoring, cla/signed

#4785 Get `DbConnection::renderFilterExpression()` up to date
  library/Icinga/Data/Db/DbConnection.php
Labels: cla/signed

#4697 Feature/redesigned user menu
  application/views/scripts/layout/menu.phtml
  library/Icinga/Web/Menu.php
  library/Icinga/Web/Navigation/ConfigMenu.php
  library/Icinga/Web/Navigation/Renderer/BadgeNavigationItemRenderer.php
  library/Icinga/Web/StyleSheet.php
  modules/monitoring/configuration.php
  public/css/icinga/configmenu.less
  public/css/icinga/layout.less
  public/css/icinga/menu.less
  public/css/icinga/widgets.less
  public/js/icinga/behavior/navigation.js
Labels: enhancement, area/ui, cla/signed

#4765 Drop ini backend support
  application/controllers/AccountController.php
  application/forms/Config/General/ApplicationConfigForm.php
  application/forms/Config/GeneralConfigForm.php
  doc/03-Configuration.md
  doc/07-Preferences.md
  doc/80-Upgrading.md
  library/Icinga/Authentication/Auth.php
  library/Icinga/User/Preferences/PreferencesStore.php
  library/Icinga/User/Preferences/Store/DbStore.php
  library/Icinga/User/Preferences/Store/IniStore.php
  modules/migrate/application/clicommands/PreferencesCommand.php
  modules/migrate/library/Migrate/Config/UserDomainMigration.php
  modules/setup/library/Setup/Steps/GeneralConfigStep.php
  test/php/library/Icinga/User/Store/IniStoreTest.php
  test/php/library/Icinga/User/Store/PreferencesStoreTest.php
Labels: cla/signed

#4793 PdfExport: Show decoded url in pdf footer
  library/Icinga/Common/PdfExport.php
Labels: cla/signed

#4764 ui.js: Don't trigger `layout-change` before the app is initialized
  public/js/icinga/ui.js
Labels: bug, area/javascript, cla/signed

#4775 SingleValueSearchControl: Add default class to the search suggestions
  library/Icinga/Web/Widget/SingleValueSearchControl.php
Labels: cla/signed

#4696 Display announcements in fullscreen-layout
  public/css/icinga/layout-structure.less
Labels: enhancement, cla/signed
