Repository Icinga/icingaweb2, pull requests merged in 2022-10, with the labels that each got.

#4891 Unveil hidden downtime in checkable detail view
  modules/monitoring/application/views/scripts/show/components/downtime.phtml
Labels: cla/signed

#4901 Fix LDAP pagination for PHP7.3+
  library/Icinga/Protocol/Ldap/LdapConnection.php
Labels: bug, cla/signed

#4921 Macro: Log the object where a macro is not found
  modules/monitoring/library/Monitoring/Object/Macro.php
Labels: bug, area/monitoring, cla/signed

#4892 Dashlet: Drop `view` parameter from title urls
  library/Icinga/Web/Widget/Dashboard/Dashlet.php
Labels: cla/signed

#4884 Enhance collapsible js
  application/forms/Security/RoleForm.php
  library/Icinga/Web/View/PrivilegeAudit.php
  modules/monitoring/public/css/module.less
  public/css/icinga/audit.less
  public/css/icinga/base.less
  public/css/icinga/main.less
  public/css/icinga/widgets.less
  public/js/icinga/behavior/collapsible.js
  public/js/icinga/utils.js
Labels: enhancement, area/javascript, cla/signed

#4931 css: Optimize performance
  public/css/icinga/forms.less
Labels: bug, area/ui, cla/signed

#4936 CommentParser: Wrap outputs after `120` chars and not `72`
  library/Icinga/Cli/Documentation/CommentParser.php
Labels: cla/signed
