Repository Icinga/icingaweb2, pull requests merged in 2023-10, with the labels that each got.

#5144 Update phpstan-baseline.neon
  phpstan-baseline.neon
Labels: cla/signed

#5130 Fix `PostgreSQL` grants
  library/Icinga/Application/MigrationManager.php
  modules/setup/application/forms/DbResourcePage.php
  modules/setup/library/Setup/Utils/DbTool.php
  modules/setup/library/Setup/WebWizard.php
  phpstan-baseline.neon
Labels: bug, area/installation, cla/signed

#5145 doc: Fix link pointing to graphite's CSP support release
  doc/20-Advanced-Topics.md
Labels: bug, area/documentation, cla/signed

#5143 Fix redirection loop
  library/Icinga/Web/Response.php
  public/js/icinga/loader.js
Labels: bug, area/javascript, cla/signed
