Repository Icinga/icingaweb2, pull requests merged in 2023-09, with the labels that each got.

#5102 PHPStan Baseline: Remove `ipl\Html\BaseHtmlElement::$defaultAttributes` type hint error patterns
  phpstan-baseline.neon
Labels: cla/signed

#5101 Fix CSP link in configuration documentation
  doc/03-Configuration.md
Labels: bug, cla/signed

#5104 JsonResponse: Fix documentation of `sendResponse`
  library/Icinga/Web/Response/JsonResponse.php
Labels: cla/signed

#4923 allow configuring the landing page
  application/controllers/IndexController.php
  doc/20-Advanced-Topics.md
Labels: enhancement, cla/signed

#5063 Make `host` optional for `oci` database resources
  application/forms/Config/Resource/DbResourceForm.php
  library/Icinga/Application/Platform.php
Labels: bug, cla/signed

#5049 ui.js: Add event `column-moved`
  public/js/icinga/ui.js
Labels: enhancement, area/javascript, cla/signed

#5055 Fix:Remove detail url when no item selected
  public/js/icinga/loader.js
  public/js/icinga/ui.js
Labels: bug, area/javascript, cla/signed

#5047 Fix incorrect message for invalid states
  modules/monitoring/library/Monitoring/Object/Host.php
  modules/monitoring/library/Monitoring/Object/Service.php
Labels: bug, area/monitoring, cla/signed

#5106 loader.js: Don't refresh twice upon `__CLOSE__`
  public/js/icinga/loader.js
Labels: area/javascript, area/framework, cla/signed

#5108 loader.js: Allow to initiate a refresh with `__REFRESH__`
  public/js/icinga/loader.js
Labels: area/javascript, area/framework, cla/signed

#5107 loader.js: Don't attempt to load an extra update to a closed column
  public/js/icinga/loader.js
Labels: bug, area/javascript, cla/signed

#5075 Release GHA: create only one Docker image at the same time
  .github/workflows/docker.yml
Labels: cla/signed

#5094 Fix setup wizard
  application/forms/Config/Resource/DbResourceForm.php
  modules/setup/application/forms/AdminAccountPage.php
  modules/setup/application/forms/DatabaseCreationPage.php
  public/css/icinga/setup.less
Labels: cla/signed

#5088 Remove redundant gravatar in contact detail
  application/controllers/StaticController.php
  modules/monitoring/application/views/scripts/show/contact.phtml
  phpstan-baseline.neon
Labels: cla/signed

#5109 Response: Fix backwards compatibilty for `__CLOSE__`
  library/Icinga/Web/Response.php
Labels: bug, area/navigation, cla/signed

#5111 css: Register missing ipl-web less variable overrides
  public/css/icinga/base.less
Labels: area/framework, area/ui, cla/signed

#5113 WebWizard: Define `icingaweb_schema` as database table
  modules/setup/library/Setup/WebWizard.php
Labels: bug, area/installation, cla/signed

#5115 X509\Sni: Clear backend instances before performing actual DB queries
  modules/monitoring/library/Monitoring/ProvidedHook/X509/Sni.php
Labels: cla/signed

#5116 DbMigrationHook: Pad matching groups to the desired length before using them
  library/Icinga/Application/Hook/DbMigrationHook.php
Labels: bug, cla/signed

#5121 Use `main` instead of `master` as default branch name
  .github/workflows/L10n-update.yml
  .github/workflows/docker.yml
  .github/workflows/php.yml
  CONTRIBUTING.md
  README.md
  RELEASE.md
  doc/01-About.md
Labels: cla/signed

#5120 Release v2.12.0
  AUTHORS
  CHANGELOG.md
  VERSION
  application/views/scripts/error/error.phtml
  doc/02-Installation.md
  library/Icinga/Application/Version.php
  modules/doc/module.info
  modules/migrate/module.info
  modules/monitoring/module.info
  modules/setup/library/Setup/WebWizard.php
  modules/setup/module.info
  modules/test/module.info
  modules/translation/module.info
Labels: cla/signed

#5123 AdminAccountPage: Fix LDAP setup error
  modules/setup/application/forms/AdminAccountPage.php
Labels: bug, area/installation, cla/signed

#5127 Always reload window when redirecting to the login
  library/Icinga/Web/Controller/ActionController.php
Labels: bug, area/ui, cla/signed
