Repository Icinga/icingaweb2, pull requests merged in 2023-06, with the labels that each got.

#5042 php: Fix mysql container startup
  .github/workflows/php.yml
Labels: cla/signed

#5039 base.less: Make menu nav-level-2 hover better visible
  public/css/icinga/base.less
Labels: enhancement, area/ui, cla/signed

#5041 Javascript: Add `copy-to-clipboard` behavior
  library/Icinga/Web/JavaScript.php
  public/js/icinga/behavior/copy-to-clipboard.js
Labels: enhancement, area/javascript, cla/signed

#5044 js: Automatically transform `.time-until` widgets into `.time-ago` ones
  public/js/icinga/ui.js
Labels: area/javascript, area/framework, cla/signed

#5005 IcingaException: Only use `vsprintf()` if `$args` given
  library/Icinga/Exception/IcingaException.php
Labels: bug, cla/signed

#5033 RoleForm: Force a suffix for all element names
  application/forms/Security/RoleForm.php
Labels: bug, area/configuration, cla/signed

#5035 TimeLine: Always parse `int` to validateTime()
  modules/monitoring/library/Monitoring/Timeline/TimeLine.php
Labels: bug, area/monitoring, cla/signed

#5010 MonitoringBadgeNavigationItemRenderer: do not fail
  modules/monitoring/library/Monitoring/Web/Navigation/Renderer/MonitoringBadgeNavigationItemRenderer.php
Labels: bug, area/monitoring, cla/signed

#5036 Fix installation doc for centOS
  doc/02-Installation.md
Labels: bug, area/documentation, cla/signed

#5021 Fixes #5020
  modules/monitoring/library/Monitoring/Backend/Ido/Query/HostdowntimeendhistoryQuery.php
  modules/monitoring/library/Monitoring/Backend/Ido/Query/HostdowntimestarthistoryQuery.php
  modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicedowntimeendhistoryQuery.php
  modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicedowntimestarthistoryQuery.php
Labels: bug, area/monitoring, cla/signed
