Repository Icinga/icingaweb2, pull requests merged in 2023-08, with the labels that each got.

#5077 test: Support `ICINGAWEB_CONFIGDIR` during bootstrapping
  test/php/bootstrap.php
Labels: cla/signed

#5080 Check if `\Throwable` instead of `\Exception`..
  library/Icinga/Application/Logger.php
  library/Icinga/Exception/IcingaException.php
Labels: bug, cla/signed

#5065 js: Enhance server side container closing
  public/js/icinga/behavior/modal.js
  public/js/icinga/loader.js
Labels: area/javascript, cla/signed

#5066 js: Always load redirects to their designated target
  library/Icinga/Web/Response.php
  public/js/icinga/loader.js
Labels: area/javascript, cla/signed

#5069 loader.js: Fix extra updates values inconsistency
  public/js/icinga/loader.js
Labels: bug, area/javascript, cla/signed

#5061 Remove unused `FilterWidget::class`
  library/Icinga/Web/Widget/FilterEditor.php
  library/Icinga/Web/Widget/FilterWidget.php
Labels: cla/signed

#5084 PdfExport: Fix empty content in exported pdf
  library/Icinga/Common/PdfExport.php
Labels: bug, area/export, cla/signed

#5059 Allow Enabling Strict Content Security Policy (CSP)
  application/controllers/ConfigController.php
  application/forms/Config/General/ApplicationConfigForm.php
  doc/03-Configuration.md
  doc/20-Advanced-Topics.md
  library/Icinga/Util/Csp.php
  library/Icinga/Web/Controller/ActionController.php
  library/Icinga/Web/Response.php
Labels: enhancement, area/framework, cla/signed

#4882 loader.js: Don't update history for redirects
  public/js/icinga/loader.js
Labels: bug, area/javascript, cla/signed

#5090 ActionController: Always read icingaweb config for csp
  library/Icinga/Web/Controller/ActionController.php
Labels: bug, cla/signed

#5095 Test: Load a module's composer autoloader
  library/Icinga/Application/Test.php
Labels: cla/signed

#5096 css: Hide details marker of collapsibles in Safari
  public/css/icinga/main.less
Labels: bug, area/ui, cla/signed
