Repository Icinga/icingaweb2, pull requests merged in 2023-01, with the labels that each got.

#4964 Packaging Adjustments
  .gitattributes
  LICENSE
  doc/20-Advanced-Topics.md
  doc/80-Upgrading.md
  doc/90-SELinux.md
  modules/setup/library/Setup/WebWizard.php
  packages/RPM.md
  packages/files/apache/icingaweb2.conf
  packages/files/apache/icingaweb2.fpm.conf
  packages/files/bin/icingacli
  packages/files/config/modules/doc/config.ini
  packages/files/config/modules/setup/config.ini
  packages/files/config/modules/translation/config.ini
  packages/files/public/index.php
  packages/selinux/icingaweb2.fc
  packages/selinux/icingaweb2.if
  packages/selinux/icingaweb2.sh
  packages/selinux/icingaweb2.te
  schema/mysql-upgrades/2.0.0beta3-2.0.0rc1.sql
  schema/mysql-upgrades/2.11.0.sql
  schema/mysql-upgrades/2.5.0.sql
  schema/mysql-upgrades/2.9.0.sql
  schema/mysql-upgrades/2.9.1.sql
  schema/mysql.schema.sql
  schema/pgsql-upgrades/2.0.0beta3-2.0.0rc1.sql
  schema/pgsql-upgrades/2.11.0.sql
  schema/pgsql-upgrades/2.5.0.sql
  schema/pgsql-upgrades/2.9.0.sql
  schema/pgsql-upgrades/2.9.1.sql
  schema/pgsql.schema.sql
Labels: cla/signed

#4974 Update Checkout Action to v3
  .github/workflows/php.yml
Labels: cla/signed

#4972 Check if url is external in validation function
  library/Icinga/Web/Form/Validator/InternalUrlValidator.php
Labels: bug, area/dashboard, cla/signed

#4976 js: Only disable submit buttons on form submit
  public/js/icinga/behavior/modal.js
  public/js/icinga/loader.js
Labels: area/javascript, cla/signed

#4977 js: Transmit `X-Icinga-AutoSubmittedBy` upon autosubmits
  public/js/icinga/loader.js
Labels: area/javascript, cla/signed

#4978 Libraries: Only attempt a partial match if the library name contains a slash
  library/Icinga/Application/Libraries.php
Labels: bug, area/framework, cla/signed

#4980 Fix some reflected XSS bugs
  application/views/scripts/form/reorder-authbackend.phtml
  modules/monitoring/application/views/scripts/form/reorder-command-transports.phtml
  modules/setup/application/views/scripts/form/setup-modules.phtml
  modules/setup/application/views/scripts/form/setup-requirements.phtml
  modules/setup/application/views/scripts/form/setup-summary.phtml
Labels: bug, cla/signed

#4983 TemporaryLocalFileStorage: Fix unexpected crash in destructor
  library/Icinga/File/Storage/TemporaryLocalFileStorage.php
Labels: bug, cla/signed

#4986 Enhance module test compatibility
  library/Icinga/Test/BaseTestCase.php
  test/php/bootstrap.php
Labels: cla/signed

#4987 icingacli setup config webserver apache: add trailing / to Alias dir
  modules/setup/library/Setup/Webserver.php
  modules/setup/library/Setup/Webserver/Apache.php
Labels: cla/signed

#4988 Provide the behaviour the Docker images patch into us by ourselves
  application/forms/Config/General/LoggingConfigForm.php
  modules/setup/application/views/scripts/form/setup-welcome.phtml
Labels: cla/signed
