Repository Icinga/icingaweb2, pull requests merged in 2024-11, with the labels that each got.

#5239 About Page: Suppress the MigrationManager exception
  application/views/scripts/about/index.phtml
Labels: bug, area/ui, cla/signed

#5282 fix(csv): fix #5279 always force subject to be a string in str_replace
  library/Icinga/File/Csv.php
Labels: bug, area/export, area/cli, cla/signed

#5278 navigation/dashboard.phtml: Use ipl-web's Icon for fa- icons
  application/views/scripts/navigation/dashboard.phtml
  library/Icinga/Web/View.php
  library/Icinga/Web/View/helpers/url.php
Labels: enhancement, area/framework, area/ui, cla/signed

#5262 .deb: let user install icinga-archive-keyring package
  doc/02-Installation.md
Labels: cla/signed

#5229 Don't rpm --import https://packages.icinga.com/icinga.key
  doc/02-Installation.md
Labels: cla/signed

#5214 ApplicationConfigForm: fix typo
  application/forms/Config/General/ApplicationConfigForm.php
Labels: cla/signed

#5016 CSS: Set correct height input[type=“datetime-local”]
  public/css/icinga/forms.less
Labels: area/ui, cla/signed

#5190 Form submission: Identify pressed submit button associated through form attribute
  public/js/icinga/behavior/modal.js
  public/js/icinga/events.js
Labels: enhancement, area/javascript, cla/signed

#5283 CustomVarRendererHook: Log an exception's message and location
  modules/monitoring/library/Monitoring/Hook/CustomVarRendererHook.php
Labels: bug, area/framework, cla/signed

#5284 CustomVarTable: Let the user subgroups fully collapse
  modules/monitoring/library/Monitoring/Web/Widget/CustomVarTable.php
Labels: area/framework, area/ui, cla/signed

#5285 Fix sort roles by name
  application/controllers/RoleController.php
  library/Icinga/Authentication/RolesConfig.php
  library/Icinga/Data/DataArray/ArrayDatasource.php
  test/php/library/Icinga/Data/DataArray/ArrayDatasourceTest.php
Labels: bug, cla/signed

#5250 Add hint for comments in ini files
  doc/03-Configuration.md
Labels: area/documentation, cla/signed

#5289 Release/v2.12.2
  .mailmap
  AUTHORS
  CHANGELOG.md
  VERSION
  library/Icinga/Application/Version.php
  modules/doc/module.info
  modules/migrate/module.info
  modules/monitoring/module.info
  modules/setup/module.info
  modules/test/module.info
  modules/translation/module.info
Labels: cla/signed

#5291 fix(icons): Service States are not aligned, fix #5290
  library/Icinga/Web/View.php
Labels: cla/signed

#5296 form.js: Ignore buttons again when being asked to render content
  public/js/icinga/behavior/form.js
Labels: bug, area/javascript, area/monitoring, cla/signed
