Repository Icinga/icingaweb2, pull requests merged in 2024-08, with the labels that each got.

#5182 Fix that graphs disappear after using form controls
  public/js/icinga.js
  public/js/icinga/behavior/detach.js
  public/js/icinga/behavior/form.js
  public/js/icinga/loader.js
Labels: bug, area/javascript, cla/signed

#5181 Add missing script-src policy
  library/Icinga/Util/Csp.php
  public/js/icinga/behavior/collapsible.js
Labels: bug, cla/signed

#5201 Fix broken UI when trying to resolve an undefined `$macro$`
  modules/monitoring/library/Monitoring/Object/Macro.php
  phpstan-baseline-7x.neon
  phpstan-baseline-8x.neon
  phpstan-baseline-standard.neon
Labels: bug, cla/signed

#5170 list/history: Use intl's default locale to format time and date
  application/views/scripts/error/error.phtml
  doc/02-Installation.md
  modules/monitoring/application/views/scripts/partials/event-history.phtml
  modules/setup/library/Setup/WebWizard.php
Labels: bug, cla/signed

#5179 js: Explicitly update history when col2 is closed
  public/js/icinga/behavior/actiontable.js
  public/js/icinga/ui.js
Labels: bug, area/navigation, cla/signed

#5185 navigation/dashboard: Provide fallback for icingadb items without icon
  application/views/scripts/navigation/dashboard.phtml
Labels: bug, area/navigation, cla/signed

#5186 DeleteDowntimesCommandForm: Ignore 404's
  modules/monitoring/application/forms/Command/Object/DeleteDowntimesCommandForm.php
Labels: bug, ref/IP, cla/signed

#5206 LdapConnection: Access array key only if its set
  library/Icinga/Protocol/Ldap/LdapConnection.php
Labels: bug, cla/signed

#5212 DbResourcePage: Warn the user if Icinga DB is used as configuration database
  modules/setup/application/forms/DbResourcePage.php
Labels: bug, cla/signed

#5169 removed gendered language
  application/controllers/NavigationController.php
  modules/monitoring/library/Monitoring/Hook/HostActionsHook.php
  modules/monitoring/library/Monitoring/Hook/ServiceActionsHook.php
  modules/setup/application/views/scripts/form/setup-welcome.phtml
  modules/setup/library/Setup/Steps/UserGroupStep.php
  test/php/library/Icinga/UserTest.php
Labels: cla/signed

#5240 Css: Do not allow `:hover` to affect the `.active` list elements
  modules/monitoring/public/css/tables.less
  public/css/icinga/main.less
Labels: area/ui, cla/signed

#5226 Add Icinga Director to list of components capable of strict CSP
  doc/20-Advanced-Topics.md
Labels: cla/signed

#5037 Flyout menu: Render menu `bottom-up` if it exceeds the viewport height
  public/css/icinga/menu.less
  public/js/icinga/behavior/navigation.js
Labels: bug, area/javascript, cla/signed

#5247 add MariaDB to installation doc
  doc/02-Installation.md
  doc/05-Authentication.md
  doc/07-Preferences.md
Labels: cla/signed
