Repository Icinga/icingaweb2, pull requests merged in 2025-04, with the labels that each got.

#5347 Dashlet: Properly embed iframe urls
  library/Icinga/Web/Widget/Dashboard/Dashlet.php
  public/js/icinga/events.js
Labels: bug, area/dashboard, cla/signed

#5351 Patch-Csv.php-for-0-values
  library/Icinga/File/Csv.php
Labels: bug, area/export, area/cli, cla/signed

#5357 Fix browser timezone information being lost
  library/Icinga/Util/TimezoneDetect.php
  public/js/icinga/timezone.js
  test/php/library/Icinga/Util/TimezoneDetectTest.php
Labels: cla/signed

#5363 Fix menu caret positioning
  public/css/icinga/menu.less
  public/js/icinga/behavior/navigation.js
Labels: area/ui, cla/signed

#5360 Show title in level-2 flyouts
  library/Icinga/Web/Menu.php
  library/Icinga/Web/Navigation/Renderer/RecursiveMenuNavigationRenderer.php
  library/Icinga/Web/Navigation/Renderer/RecursiveNavigationRenderer.php
  public/css/icinga/menu.less
Labels: cla/signed
