Repository Icinga/icingaweb2, pull requests merged in 2025-08, with the labels that each got.

#5411 Fix/icingacli setup fpm flag
  modules/setup/application/clicommands/ConfigCommand.php
  modules/setup/library/Setup/Webserver/Apache.php
Labels: bug, area/configuration, area/cli, cla/signed

#5407 Fix: PHP built-in server detection for PHP 8.3 SERVER_SOFTWARE format
  library/Icinga/Application/webrouter.php
Labels: cla/signed

#5414 Doc: fix over-escaping
  doc/05-Authentication.md
Labels: bug, area/documentation, cla/signed

#5327 Fix typo in code comment
  library/Icinga/Application/webrouter.php
Labels: cla/signed

#5416 Fix typo in code comment
  library/Icinga/Web/Form.php
Labels: cla/signed
