Repository Icinga/icingaweb2, pull requests merged in 2025-03, with the labels that each got.

#5314 RolesConfig: Add missing column `name` for quick search
  library/Icinga/Authentication/RolesConfig.php
Labels: bug, cla/signed

#5329 Fix unescaped error messages
  application/views/scripts/config/module-configuration-error.phtml
  modules/monitoring/application/forms/Config/BackendConfigForm.php
Labels: bug, cla/signed

#5338 Fix case sensitive authentication with postgres
  library/Icinga/Authentication/User/DbUserBackend.php
  library/Icinga/Authentication/UserGroup/DbUserGroupBackend.php
Labels: bug, area/authentication, cla/signed

#5332 Fix doc module markdown table rows in light mode
  modules/doc/public/css/module.less
Labels: bug, area/documentation, area/ui, cla/signed

#5340 monitoring: Use the (new) icon for the reporting section
  modules/monitoring/configuration.php
Labels: area/ui, cla/signed

#5313 tabs.less: Don't let icinga-loader element overlap the dropdown nav
  public/css/icinga/tabs.less
Labels: area/ui, cla/signed

#5341 Pdf: Ensure dompdf can create temporary files
  library/Icinga/File/Pdf.php
Labels: cla/signed

#5342 Release/v2.12.3
  CHANGELOG.md
  VERSION
  application/views/scripts/error/error.phtml
  doc/02-Installation.md
  library/Icinga/Application/Version.php
  modules/doc/module.info
  modules/migrate/module.info
  modules/monitoring/module.info
  modules/setup/library/Setup/WebWizard.php
  modules/setup/module.info
  modules/test/module.info
  modules/translation/module.info
Labels: cla/signed

#5344 DbUserBackend: Fix broken password hash fetch routine
  library/Icinga/Authentication/User/DbUserBackend.php
Labels: bug, area/authentication, cla/signed

#5345 Release/v2.12.4
  CHANGELOG.md
  VERSION
  library/Icinga/Application/Version.php
  modules/doc/module.info
  modules/migrate/module.info
  modules/monitoring/module.info
  modules/setup/module.info
  modules/test/module.info
  modules/translation/module.info
Labels: cla/signed
