Repository Icinga/icingaweb2, pull requests merged in 2025-05, with the labels that each got.

#5365 Support setting a default comment for acknowledgements
  modules/monitoring/application/forms/Command/Object/AcknowledgeProblemCommandForm.php
  modules/monitoring/doc/03-Configuration.md
Labels: cla/signed

#5359 Disable deprecation warnings unless ICINGAWEB_ENVIRONMENT is set to "dev"
  library/Icinga/Application/ApplicationBootstrap.php
  library/Icinga/Application/webrouter.php
  test/php/library/Icinga/File/Storage/LocalFileStorageTest.php
Labels: cla/signed

#5364 Fix: split fpm-uri flag in socket and url flag
  modules/setup/application/clicommands/ConfigCommand.php
  modules/setup/library/Setup/Webserver.php
  modules/setup/library/Setup/Webserver/Apache.php
  modules/setup/library/Setup/Webserver/Nginx.php
Labels: cla/signed

#5362 ServicestatusQuery: Fix that timestamp columns work with relative time filter
  doc/80-Upgrading.md
  modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicestatusQuery.php
Labels: bug, cla/signed

#5367 Menu navigation: Improve flyout transition
  public/js/icinga/behavior/navigation.js
Labels: enhancement, area/javascript, area/navigation, cla/signed

#5355 Fix: spacing and text-breaking
  public/css/icinga/layout.less
  public/css/icinga/menu.less
Labels: cla/signed

#5334 Fix/collapsed active menu item indicator
  public/css/icinga/menu.less
Labels: cla/signed
